package gov.hhs.acf.cb.nytd.models;

// Generated May 20, 2009 10:16:43 AM by Hibernate Tools 3.2.4.GA

import java.math.BigDecimal;

/*
 * AggregateValue generated by hbm2java
 */
public class AggregateValue extends PersistentObject
{
	private String name;
	private Integer countValue;
	private BigDecimal percentValue;

	public AggregateValue()
	{
	}

	public String getName()
	{
		return this.name;
	}

	public void setName(String name)
	{
		this.name = name;
	}

	public Integer getCountValue()
	{
		return this.countValue;
	}

	public void setCountValue(Integer countValue)
	{
		this.countValue = countValue;
	}

	/**
	 * @return the percentValue
	 */
	public BigDecimal getPercentValue()
	{
		return percentValue;
	}

	/**
	 * @param percentValue the percentValue to set
	 */
	public void setPercentValue(BigDecimal percentValue)
	{
		this.percentValue = percentValue;
	}
}
