package gov.hhs.acf.cb.nytd.models;

//Generated Jul 15, 2009 11:56:32 AM by Hibernate Tools 3.2.4.GA

import java.util.HashSet;
import java.util.Set;


/*
 * * Allowedvalueinconsistency generated by hbm2java
 */
public class AllowedValueInconsistency extends PersistentObject
{

	private AllowedValue allowedValue;
	private ProblemDescription problemDescription;
	private Boolean isTrue;
	
	public AllowedValueInconsistency()
	{
	}

	public AllowedValueInconsistency(Long allowedValueInconsistencyId)
	{
		this.id = allowedValueInconsistencyId;
	}
	
	public AllowedValueInconsistency(Long allowedValueInconsistencyId, AllowedValue allowedValue,
			ProblemDescription problemdescriptionid, Boolean isTrue,
			Set<CrossRefInconsistency> crossRefInconsistencies)
	{
		super();
		this.id = allowedValueInconsistencyId;
		this.allowedValue = allowedValue;
		this.problemDescription = problemdescriptionid;
		this.isTrue = isTrue;
		this.crossRefInconsistencies = crossRefInconsistencies;
	}

	private Set<CrossRefInconsistency> crossRefInconsistencies = new HashSet<CrossRefInconsistency>(0);

	/**
	 * @return the allowedValue
	 */
	public AllowedValue getAllowedValue()
	{
		return allowedValue;
	}

	/**
	 * @param allowedValue the allowedValue to set
	 */
	public void setAllowedValue(AllowedValue allowedValue)
	{
		this.allowedValue = allowedValue;
	}

	/**
	 * @return the problemdescriptionid
	 */
	public ProblemDescription getProblemDescription()
	{
		return problemDescription;
	}

	/**
	 * @param problemdescriptionid the problemdescriptionid to set
	 */
	public void setProblemDescription(ProblemDescription problemdescriptionid)
	{
		this.problemDescription = problemdescriptionid;
	}


	/**
	 * @return the isTrue
	 */
	public Boolean getIsTrue()
	{
		return isTrue;
	}

	/**
	 * @param isTrue the isTrue to set
	 */
	public void setIsTrue(Boolean isTrue)
	{
		this.isTrue = isTrue;
	}

	/**
	 * @return the crossRefInconsistencies
	 */
	public Set<CrossRefInconsistency> getCrossRefInconsistencies()
	{
		return crossRefInconsistencies;
	}

	/**
	 * @param crossRefInconsistencies the crossRefInconsistencies to set
	 */
	public void setCrossRefInconsistencies(Set<CrossRefInconsistency> crossRefInconsistencies)
	{
		this.crossRefInconsistencies = crossRefInconsistencies;
	}


}
