package gov.hhs.acf.cb.nytd.models;

import java.util.Calendar;

// Generated May 20, 2009 10:16:43 AM by Hibernate Tools 3.2.4.GA

/*
 * AllowedValue generated by hbm2java
 */
public class AllowedValue extends PersistentObject
{

	private Population population;
	/*private DataQualityAdvStandard dataQualityAdvStandard;*/
	private ElementLevelDQAStandard elementLevelDQAStandard;
	private Element element;
	private String name;
	private String value;

	public AllowedValue()
	{
	}

	public AllowedValue(Long allowedValueId)
	{
		this.id = allowedValueId;
	}

	public AllowedValue(Long allowedValueId, Population population, ElementLevelDQAStandard elementLevelDQAStandard, Element element, String name,
			String value, Calendar createdDate, String createdBy, Calendar updateDate, String updateBy,
			String description)
	{
		this.id = allowedValueId;
		this.population = population;
	//	this.dataQualityAdvStandard = dataQualityAdvStandard;
		this.elementLevelDQAStandard = elementLevelDQAStandard;
		this.element = element;
		this.name = name;
		this.value = value;
		this.createdDate = createdDate;
		this.createdBy = createdBy;
		this.updateDate = updateDate;
		this.updateBy = updateBy;
		this.description = description;
	}

	public Population getPopulation()
	{
		return this.population;
	}

	public void setPopulation(Population population)
	{
		this.population = population;
	}
	
	

/*	public DataQualityAdvStandard getDataQualityAdvStandard() {
		return dataQualityAdvStandard;
	}

	public void setDataQualityAdvStandard(DataQualityAdvStandard dataQualityAdvStandard) {
		this.dataQualityAdvStandard = dataQualityAdvStandard;
	}*/

	public Element getElement()
	{
		return this.element;
	}

	public void setElement(Element element)
	{
		this.element = element;
	}

	public String getName()
	{
		return this.name;
	}

	public void setName(String name)
	{
		this.name = name;
	}

	public String getValue()
	{
		return this.value;
	}

	public void setValue(String value)
	{
		this.value = value;
	}

	/**
	 * @return the elementLevelDQAStandard
	 */
	public ElementLevelDQAStandard getElementLevelDQAStandard()
	{
		return elementLevelDQAStandard;
	}

	/**
	 * @param elementLevelDQAStandard the elementLevelDQAStandard to set
	 */
	public void setElementLevelDQAStandard(ElementLevelDQAStandard elementLevelDQAStandard)
	{
		this.elementLevelDQAStandard = elementLevelDQAStandard;
	}

}
