package gov.hhs.acf.cb.nytd.models;

import java.util.Calendar;

// Generated May 20, 2009 10:16:43 AM by Hibernate Tools 3.2.4.GA

/*
 * ComplianceStandard generated by hbm2java
 */
public class ComplianceStandard extends PersistentObject
{
	private Element element;
	private Integer complianceStandard;
	private String penaltyLetterDesc;

	

	public ComplianceStandard()
	{
	}

	public ComplianceStandard(Long complianceStandardId)
	{
		this.id = complianceStandardId;
	}

	public ComplianceStandard(Long complianceStandardId, Element element, Integer complianceStandard,
			Calendar createdDate, String createdBy, Calendar updateDate, String updateBy, String description,
			String penaltyLetterDesc)
	{
		this.id = complianceStandardId;
		this.element = element;
		this.complianceStandard = complianceStandard;
		this.createdDate = createdDate;
		this.createdBy = createdBy;
		this.updateDate = updateDate;
		this.updateBy = updateBy;
		this.description = description;
		this.penaltyLetterDesc = penaltyLetterDesc;
	}

	public Element getElement()
	{
		return this.element;
	}

	public void setElement(Element element)
	{
		this.element = element;
	}

	public Integer getComplianceStandard()
	{
		return this.complianceStandard;
	}

	public void setComplianceStandard(Integer complianceStandard)
	{
		this.complianceStandard = complianceStandard;
	}
	/**
	 * @return the penaltyLetterDesc
	 */
	public String getPenaltyLetterDesc()
	{
		return penaltyLetterDesc;
	}

	/**
	 * @param penaltyLetterDesc the penaltyLetterDesc to set
	 */
	public void setPenaltyLetterDesc(String penaltyLetterDesc)
	{
		this.penaltyLetterDesc = penaltyLetterDesc;
	}

}
