package gov.hhs.acf.cb.nytd.models;

// Generated May 20, 2009 10:16:43 AM by Hibernate Tools 3.2.4.GA

import java.math.BigDecimal;
import java.util.Calendar;
import java.util.HashSet;
import java.util.Set;

/*
 * ComplianceCategory generated by hbm2java
 */
public class ComplianceCategory extends PersistentObject
{

	private ComplianceSuperCategory complianceSuperCategory;
	private String name;
	private BigDecimal standardPenaltyValue;
	private String penaltyLetterDesc;
	private String penaltyLetterDesc2;

	private Set<NytdError> errors = new HashSet<NytdError>(0);

	public ComplianceCategory()
	{
	}

	public ComplianceCategory(Long complianceCategoryid)
	{
		this.id = complianceCategoryid;
	}

	public ComplianceCategory(Long complianceCategoryId, ComplianceSuperCategory complianceSuperCategory,
			String name, Calendar createdDate, String createdBy, Calendar updateDate, String updateBy,
			String description, Set<NytdError> errors, String penaltyLetterDesc, String penaltyLetterDesc2)
	{
		this.id = complianceCategoryId;
		this.complianceSuperCategory = complianceSuperCategory;
		this.name = name;
		this.createdDate = createdDate;
		this.createdBy = createdBy;
		this.updateDate = updateDate;
		this.updateBy = updateBy;
		this.description = description;
		this.errors = errors;
		this.penaltyLetterDesc = penaltyLetterDesc;
		this.penaltyLetterDesc2 = penaltyLetterDesc2;
	}

	public ComplianceSuperCategory getComplianceSuperCategory()
	{
		return this.complianceSuperCategory;
	}

	public void setComplianceSuperCategory(ComplianceSuperCategory complianceSuperCategory)
	{
		this.complianceSuperCategory = complianceSuperCategory;
	}

	public String getName()
	{
		return this.name;
	}

	public void setName(String name)
	{
		this.name = name;
	}

	public Set<NytdError> getErrors()
	{
		return this.errors;
	}

	public void setErrors(Set<NytdError> errors)
	{
		this.errors = errors;
	}

	public BigDecimal getStandardPenaltyValue()
	{
		return this.standardPenaltyValue;
	}

	public void setStandardPenaltyValue(BigDecimal standardPenaltyValue)
	{
		this.standardPenaltyValue = standardPenaltyValue;
	}

	/**
	 * @return the penaltyLetterDesc
	 */
	public String getPenaltyLetterDesc()
	{
		return penaltyLetterDesc;
	}

	/**
	 * @param penaltyLetterDesc
	 *           the penaltyLetterDesc to set
	 */
	public void setPenaltyLetterDesc(String penaltyLetterDesc)
	{
		this.penaltyLetterDesc = penaltyLetterDesc;
	}

	/**
	 * @return the penaltyLetterDesc2
	 */
	public String getPenaltyLetterDesc2() {
		return penaltyLetterDesc2;
	}

	/**
	 * @param penaltyLetterDesc2 the penaltyLetterDesc2 to set
	 */
	public void setPenaltyLetterDesc2(String penaltyLetterDesc2) {
		this.penaltyLetterDesc2 = penaltyLetterDesc2;
	}
}
