package gov.hhs.acf.cb.nytd.models;

// Generated May 20, 2009 10:16:43 AM by Hibernate Tools 3.2.4.GA

import java.util.Calendar;
import java.util.HashSet;
import java.util.Set;

/*
 * ComplianceSuperCategory generated by hbm2java
 */
public class ComplianceSuperCategory extends PersistentObject
{

	private String name;

	private Set<ComplianceCategory> complianceCategories = new HashSet<ComplianceCategory>(0);

	public ComplianceSuperCategory()
	{
	}

	public ComplianceSuperCategory(Long complianceSuperCategoryId)
	{
		this.id = complianceSuperCategoryId;
	}

	public ComplianceSuperCategory(Long complianceSuperCategoryId, String name, Calendar createdDate,
			String createdBy, Calendar updateDate, String updateBy, String description,
			Set<ComplianceCategory> complianceCategories)
	{
		this.id = complianceSuperCategoryId;
		this.name = name;
		this.createdDate = createdDate;
		this.createdBy = createdBy;
		this.updateDate = updateDate;
		this.updateBy = updateBy;
		this.description = description;
		this.complianceCategories = complianceCategories;
	}

	public String getName()
	{
		return this.name;
	}

	public void setName(String name)
	{
		this.name = name;
	}

	public Set<ComplianceCategory> getComplianceCategories()
	{
		return this.complianceCategories;
	}

	public void setComplianceCategories(Set<ComplianceCategory> complianceCategories)
	{
		this.complianceCategories = complianceCategories;
	}

}
