package gov.hhs.acf.cb.nytd.models;

// Generated Jul 15, 2009 11:56:32 AM by Hibernate Tools 3.2.4.GA


/*
 * * Crossrefinconsistency generated by hbm2java
 */
public class CrossRefInconsistency extends PersistentObject
{

	private AllowedValueInconsistency allowedValueInconsistency;
	private AllowedValue allowedValue;
	private Boolean isTrue;
	
	public CrossRefInconsistency()
	{
	}

	public CrossRefInconsistency(Long crossRefInconsistencyId)
	{
		this.id = crossRefInconsistencyId;
	}

	/**
	 * @param crossRefInconsistencyId
	 * @param allowedValueInconsistency
	 * @param allowedvalueid
	 * @param istrue
	 */
	public CrossRefInconsistency(Long crossRefInconsistencyId,
			AllowedValueInconsistency allowedValueInconsistency, AllowedValue allowedvalueid, Boolean istrue)
	{
		super();
		this.id = crossRefInconsistencyId;
		this.allowedValueInconsistency = allowedValueInconsistency;
		this.allowedValue = allowedvalueid;
		this.isTrue = istrue;
	}

	/**
	 * @return the allowedValueInconsistency
	 */
	public AllowedValueInconsistency getAllowedValueInconsistency()
	{
		return allowedValueInconsistency;
	}
	/**
	 * @param allowedValueInconsistency the allowedValueInconsistency to set
	 */
	public void setAllowedValueInconsistency(AllowedValueInconsistency allowedValueInconsistency)
	{
		this.allowedValueInconsistency = allowedValueInconsistency;
	}
	/**
	 * @return the allowedValue
	 */
	public AllowedValue getAllowedValue()
	{
		return allowedValue;
	}
	/**
	 * @param allowedValue the allowedValue to set
	 */
	public void setAllowedValue(AllowedValue allowedValue)
	{
		this.allowedValue = allowedValue;
	}
	/**
	 * @return the isTrue
	 */
	public Boolean getIsTrue()
	{
		return isTrue;
	}
	/**
	 * @param isTrue the isTrue to set
	 */
	public void setIsTrue(Boolean isTrue)
	{
		this.isTrue = isTrue;
	}

}
