package gov.hhs.acf.cb.nytd.models;

import java.util.Calendar;
import java.util.HashSet;
import java.util.Set;

// Generated May 20, 2009 10:16:43 AM by Hibernate Tools 3.2.4.GA

/*
 * DataQualityAdvStandard generated by hbm2java
 */
public class DataQualityAdvStandard extends PersistentObject
{
	private String name;
	private Integer dataQualityAdvStandard;

    // associations
	private AllowedValue allowedValue;

    // collections
    private Set<DataQualityAdvAggregate> dataAggregates =
            new HashSet<DataQualityAdvAggregate>();

	public DataQualityAdvStandard()
	{
	}

	public DataQualityAdvStandard(Long dataQualityAdvStandardId)
	{
		this.id = dataQualityAdvStandardId;
	}

	public DataQualityAdvStandard(Long dataQualityAdvStandardId, String name,
			Calendar createdDate, String createdBy, Calendar updateDate, String updateBy, String description)
	{
		this.id = dataQualityAdvStandardId;
		// this.element = element;
		this.name = name;
		this.createdDate = createdDate;
		this.createdBy = createdBy;
		this.updateDate = updateDate;
		this.updateBy = updateBy;
		this.description = description;
	}
	/*
	public Element getElement()
	{
		return this.element;
	}

	public void setElement(Element element)
	{
		this.element = element;
	}
	*/
	public String getName()
	{
		return this.name;
	}

	public void setName(String name)
	{
		this.name = name;
	}

	/**
	 * @return the dataQualityAdvStandard
	 */
	public Integer getDataQualityAdvStandard()
	{
		return dataQualityAdvStandard;
	}

	/**
	 * @param dataQualityAdvStandard the dataQualityAdvStandard to set
	 */
	public void setDataQualityAdvStandard(Integer dataQualityAdvStandard)
	{
		this.dataQualityAdvStandard = dataQualityAdvStandard;
	}
	
	public AllowedValue getAllowedValue()
	{
		return allowedValue;
	}
	
	public void setAllowedValue(AllowedValue allowedValue)
	{
		this.allowedValue = allowedValue;
	}

    public Set<DataQualityAdvAggregate> getDataAggregates() {
        return dataAggregates;
    }

    public void setDataAggregates(Set<DataQualityAdvAggregate> dataAggregates) {
        this.dataAggregates = dataAggregates;
    }
}
