package gov.hhs.acf.cb.nytd.models;

import java.util.HashSet;
import java.util.Set;

// Generated May 20, 2009 10:16:43 AM by Hibernate Tools 3.2.4.GA

/*
 * DataAggregate generated by hbm2java
 */
public class DataAggregate extends AggregateValue
{
	private Lookup aggregateType;
	private Transmission transmission;
    private NonCompliance nonCompliance;
    private String complianceStatus;
    private Element element;
	private Set<AggregateValue> aggregateValues = new HashSet<AggregateValue>(0);

	public DataAggregate()
	{
	}

	public DataAggregate(Long dataAggregateId)
	{
		this.id = dataAggregateId;
	}

    /**
	 * @return the aggregateType
	 */
	public Lookup getAggregateType()
	{
		return aggregateType;
	}

	/**
	 * @param aggregateType the aggregateType to set
	 */
	public void setAggregateType(Lookup aggregateType)
	{
		this.aggregateType = aggregateType;
	}

    /**
	 * @return the transmission
	 */
	public Transmission getTransmission()
	{
		return transmission;
	}

	/**
	 * @param transmission the transmission to set
	 */
	public void setTransmission(Transmission transmission)
	{
		this.transmission = transmission;
	}

	public NonCompliance getNonCompliance()
	{
		return this.nonCompliance;
	}

	public void setNonCompliance(NonCompliance nonCompliance)
	{
		this.nonCompliance = nonCompliance;
	}

    /**
	 * @return the element
	 */
	public Element getElement()
	{
		return element;
	}

	/**
	 * @param element
	 *           the element to set
	 */
	public void setElement(Element element)
	{
		this.element = element;
	}

    /**
	 * @return the aggregateValues
	 */
	public Set<AggregateValue> getAggregateValues()
	{
		return aggregateValues;
	}

	/**
	 * @param aggregateValues
	 *           the aggregateValues to set
	 */
	public void setAggregateValues(Set<AggregateValue> aggregateValues)
	{
		this.aggregateValues = aggregateValues;
	}

    /**
	 * @return the complianceStatus
	 */
    public String getComplianceStatus() {
        return complianceStatus;
    }

    /**
	 * @param complianceStatus
	 *           the complianceStatus to set
	 */
    public void setComplianceStatus(String complianceStatus) {
        this.complianceStatus = complianceStatus;
    }
}
