package gov.hhs.acf.cb.nytd.models;

// Generated May 20, 2009 10:16:43 AM by Hibernate Tools 3.2.4.GA

import java.util.Calendar;
import java.util.HashSet;
import java.util.Set;

/*
 * Datum generated by hbm2java
 */
public class Datum extends PersistentObject
{
	private Element element;
	private TransmissionRecord transmissionRecord;
	private String value;
	private String note;

	private Set<NonCompliance> nonCompliances = new HashSet<NonCompliance>(0);
	private Set<RecordLevelAdvisory> recordLevelDQA = new HashSet<RecordLevelAdvisory>(0);

	public Datum()
	{
	}

	public Datum(Long datumid)
	{
		this.id = datumid;
	}

	public Datum(Long datumid, Element element, TransmissionRecord transmissionRecord,
			String value, Calendar createdDate, String createdBy, Calendar updateDate, String updateBy,
			String description, Set<NonCompliance> nonCompliances)
	{
		this.id = datumid;
		this.element = element;
		this.transmissionRecord = transmissionRecord;
		this.value = value;
		this.createdDate = createdDate;
		this.createdBy = createdBy;
		this.updateDate = updateDate;
		this.updateBy = updateBy;
		this.description = description;
		this.nonCompliances = nonCompliances;
	}

	public Element getElement()
	{
		return this.element;
	}

	public void setElement(Element element)
	{
		this.element = element;
	}

	public TransmissionRecord getTransmissionRecord()
	{
		return this.transmissionRecord;
	}

	public void setTransmissionRecord(TransmissionRecord transmissionRecord)
	{
		this.transmissionRecord = transmissionRecord;
	}

	public String getValue()
	{
		return this.value;
	}

	public void setValue(String value)
	{
		this.value = value;
	}

	public Set<NonCompliance> getNonCompliances()
	{
		return this.nonCompliances;
	}

	public void setNonCompliances(Set<NonCompliance> nonCompliances)
	{
		this.nonCompliances = nonCompliances;
	}

	/**
	 * @return the note
	 */
	public String getNote()
	{
		return note;
	}

	/**
	 * @param note the note to set
	 */
	public void setNote(String note)
	{
		this.note = note;
	}

	/**
	 * @return the recordLevelDQA
	 */
	public Set<RecordLevelAdvisory> getRecordLevelDQA()
	{
		return recordLevelDQA;
	}

	/**
	 * @param recordLevelDQA the recordLevelDQA to set
	 */
	public void setRecordLevelDQA(Set<RecordLevelAdvisory> recordLevelDQA)
	{
		this.recordLevelDQA = recordLevelDQA;
	}
}
