package gov.hhs.acf.cb.nytd.models;

// Generated May 20, 2009 10:16:43 AM by Hibernate Tools 3.2.4.GA

import java.util.Calendar;
import java.util.HashSet;
import java.util.Set;

/*
 * DerivedRole generated by hbm2java
 */
public class DerivedRole extends PersistentObject
{
	private SecondaryUserRole secondaryUserRole;
	private PrimaryUserRole primaryUserRole;
	private String name;

	private Set<Privilege> privileges = new HashSet<Privilege>(0);

	public DerivedRole()
	{
	}

	public DerivedRole(Long derivedRoleId)
	{
		this.id = derivedRoleId;
	}

	public DerivedRole(Long derivedRoleId, SecondaryUserRole secondaryUserRole,
			PrimaryUserRole primaryUserRole, String name, Calendar createdDate, String createdBy,
			Calendar updateDate, String updateBy, String description,
			Set<Privilege> privileges)
	{
		this.id = derivedRoleId;
		this.secondaryUserRole = secondaryUserRole;
		this.primaryUserRole = primaryUserRole;
		this.name = name;
		this.createdDate = createdDate;
		this.createdBy = createdBy;
		this.updateDate = updateDate;
		this.updateBy = updateBy;
		this.description = description;
		this.privileges = privileges;
	}

	public SecondaryUserRole getSecondaryUserRole()
	{
		return this.secondaryUserRole;
	}

	public void setSecondaryUserRole(SecondaryUserRole secondaryUserRole)
	{
		this.secondaryUserRole = secondaryUserRole;
	}

	public PrimaryUserRole getPrimaryUserRole()
	{
		return this.primaryUserRole;
	}

	public void setPrimaryUserRole(PrimaryUserRole primaryUserRole)
	{
		this.primaryUserRole = primaryUserRole;
	}

	public String getName()
	{
		return this.name;
	}

	public void setName(String name)
	{
		this.name = name;
	}

	public Set<Privilege> getPrivileges()
	{
		return this.privileges;
	}

	public void setPrivileges(Set<Privilege> privileges)
	{
		this.privileges = privileges;
	}

}
