package gov.hhs.acf.cb.nytd.models;

import java.util.Calendar;

// Generated May 20, 2009 10:16:43 AM by Hibernate Tools 3.2.4.GA

/*
 * DueDate generated by hbm2java
 */
public class DueDate extends PersistentObject
{

	// private Long dueDateId;
	private TransmissionType transmissionType;
	private ReportingPeriod reportingPeriod;
	private String name;
	private Calendar submissionDate;

	public DueDate()
	{
	}

	public DueDate(Long duedateid)
	{
		this.id = duedateid;
	}

	public DueDate(Long duedateid, TransmissionType transmissionType, ReportingPeriod reportingPeriod,
			String name, Calendar submissionDate, Calendar createdDate, String createdBy, Calendar updateDate,
			String updateBy, String description)
	{
		this.id = duedateid;
		this.transmissionType = transmissionType;
		this.reportingPeriod = reportingPeriod;
		this.name = name;
		this.submissionDate = submissionDate;
		this.createdDate = createdDate;
		this.createdBy = createdBy;
		this.updateDate = updateDate;
		this.updateBy = updateBy;
		this.description = description;
	}

	public TransmissionType getTransmissionType()
	{
		return this.transmissionType;
	}

	public void setTransmissionType(TransmissionType transmissionType)
	{
		this.transmissionType = transmissionType;
	}

	public ReportingPeriod getReportingPeriod()
	{
		return this.reportingPeriod;
	}

	public void setReportingPeriod(ReportingPeriod reportingPeriod)
	{
		this.reportingPeriod = reportingPeriod;
	}

	public String getName()
	{
		return this.name;
	}

	public void setName(String name)
	{
		this.name = name;
	}

	public Calendar getSubmissionDate()
	{
		return this.submissionDate;
	}

	public void setSubmissionDate(Calendar submissionDate)
	{
		this.submissionDate = submissionDate;
	}

}
