package gov.hhs.acf.cb.nytd.models;

import java.util.Calendar;

// Generated Jun 1, 2009 2:40:24 PM by Hibernate Tools 3.2.4.GA

/*
 * Notes generated by hbm2java
 */
public class ElementNote extends PersistentObject
{

	private Long elementNoteId;
	private Element element;
	private Transmission transmission;
	private String note;

	public ElementNote()
	{
	}

	public ElementNote(Long noteId)
	{
		this.elementNoteId = noteId;
	}

	public ElementNote(Long elementNoteId, Element element, Transmission transmission, String note, Calendar createddate,
			String createdby, Calendar updatedate, String updateby, String description)
	{
		this.elementNoteId = elementNoteId;
		this.element = element;
		this.transmission = transmission;
		this.note = note;
	}

	public Long getElementNoteId()
	{
		return this.elementNoteId;
	}

	public void setElementNoteId(Long elementNoteId)
	{
		this.elementNoteId = elementNoteId;
	}

	public Element getElement()
	{
		return this.element;
	}

	public void setElement(Element element)
	{
		this.element = element;
	}

	public Transmission getTransmission()
	{
		return this.transmission;
	}

	public void setTransmission(Transmission transmission)
	{
		this.transmission = transmission;
	}

	public String getNote()
	{
		return this.note;
	}

	public void setNote(String notes)
	{
		this.note = notes;
	}

}
