package gov.hhs.acf.cb.nytd.models;

import java.util.Calendar;

// Generated May 20, 2009 10:16:43 AM by Hibernate Tools 3.2.4.GA

/*
 * ElementPopulation generated by hbm2java
 */
public class ElementPopulation extends PersistentObject
{

	private Population population;
	private Element element;

	public ElementPopulation()
	{
	}

	public ElementPopulation(Long elementPopulationId)
	{
		this.id = elementPopulationId;
	}

	public ElementPopulation(Long elementPopulationId, Population population, Element element,
			Calendar createdDate, String createdBy, Calendar updateDate, String updateBy, String description)
	{
		this.id = elementPopulationId;
		this.population = population;
		this.element = element;
		this.createdDate = createdDate;
		this.createdBy = createdBy;
		this.updateDate = updateDate;
		this.updateBy = updateBy;
		this.description = description;
	}

	public Population getPopulation()
	{
		return this.population;
	}

	public void setPopulation(Population population)
	{
		this.population = population;
	}

	public Element getElement()
	{
		return this.element;
	}

	public void setElement(Element element)
	{
		this.element = element;
	}

}
