package gov.hhs.acf.cb.nytd.models;

// Generated May 20, 2009 10:16:43 AM by Hibernate Tools 3.2.4.GA

import java.util.Calendar;
import java.util.HashSet;
import java.util.Set;


/*
 * Element originally generated by hbm2java
 */
public class Element extends PersistentObject
{

	private String name;
	private String nodeName;
	private Integer sort;

	//private Set<ComplianceStandard> complianceStandards = new HashSet<ComplianceStandard>(0);
	private ComplianceStandard complianceStandard;
	private Set<AllowedValue> allowedValues = new HashSet<AllowedValue>(0);
	private Set<Datum> datums = new HashSet<Datum>(0);
	// private Set<DataQualityAdvStandard> dataQualityAdvStandards  = new HashSet<DataQualityAdvStandard>(0);
	private Set<ElementPopulation> elementPopulations = new HashSet<ElementPopulation>(0);
	private Set<ElementNote> elementNotes = new HashSet<ElementNote>(0);

	public Element()
	{
	}

	public Element(Long id)
	{
		this.id = id;
	}

	public Element(Long elementid, String name, Calendar createdDate, String createdBy, Calendar updateDate,
			String updateBy, String description, String nodeName, Integer sort,
			ComplianceStandard complianceStandard, Set<AllowedValue> allowedValues, Set<Datum> datums,
			Set<ElementPopulation> elementPopulations)
	{
		this.id = elementid;
		this.name = name;
		this.createdDate = createdDate;
		this.createdBy = createdBy;
		this.updateDate = updateDate;
		this.updateBy = updateBy;
		this.description = description;
		this.nodeName = nodeName;
		this.sort = sort;
		this.complianceStandard = complianceStandard;
		this.allowedValues = allowedValues;
		this.datums = datums;
		this.elementPopulations = elementPopulations;
	}

	public String getName()
	{
		return this.name;
	}

	public void setName(String name)
	{
		this.name = name;
	}

	public void setNodeName(String nodeName)
	{
		this.nodeName = nodeName;
	}

	public String getNodeName()
	{
		return nodeName;
	}

	public Integer getSort()
	{
		return sort;
	}

	public void setSort(Integer sort)
	{
		this.sort = sort;
	}

	public Set<AllowedValue> getAllowedValues()
	{
		return this.allowedValues;
	}

	public void setAllowedValues(Set<AllowedValue> allowedValues)
	{
		this.allowedValues = allowedValues;
	}

	public Set<Datum> getDatums()
	{
		return this.datums;
	}

	public void setDatums(Set<Datum> datums)
	{
		this.datums = datums;
	}

	public Set<ElementPopulation> getElementPopulations()
	{
		return this.elementPopulations;
	}

	public void setElementPopulations(Set<ElementPopulation> elementPopulations)
	{
		this.elementPopulations = elementPopulations;
	}

	/**
	 * @return the notes
	 */
	public Set<ElementNote> getElementNotes()
	{
		return elementNotes;
	}

	/**
	 * @param noteses
	 *           the notes to set
	 */
	public void setElementNotes(Set<ElementNote> notes)
	{
		this.elementNotes = notes;
	}

	/**
	 * @return the complianceStandard
	 */
	public ComplianceStandard getComplianceStandard()
	{
		return complianceStandard;
	}

	/**
	 * @param complianceStandard the complianceStandard to set
	 */
	public void setComplianceStandard(ComplianceStandard complianceStandard)
	{
		this.complianceStandard = complianceStandard;
	}

	/**
	 * @return the dataQualityAdvStandards
	 */
	/*
	public Set<DataQualityAdvStandard> getDataQualityAdvStandards()
	{
		return dataQualityAdvStandards;
	}
	*/
	/**
	 * @param dataQualityAdvStandards the dataQualityAdvStandards to set
	 */
	/*
	public void setDataQualityAdvStandards(Set<DataQualityAdvStandard> dataQualityAdvStandards)
	{
		this.dataQualityAdvStandards = dataQualityAdvStandards;
	}
	*/
}
