package gov.hhs.acf.cb.nytd.models;

//Generated May 20, 2009 10:16:43 AM by Hibernate Tools 3.2.4.GA

import java.util.Calendar;


/*
 * Lookup generated by hbm2java
 */
public class Lookup extends PersistentObject
{
	private String category;
	private Byte codeValue;
	private String codeDescription;
	private Short sortOrder;


	public Lookup()
	{
	}

	public Lookup(Long lookupId)
	{
		this.id = lookupId;
	}

	public Lookup(Long lookupId, String category, Byte codeValue, String codeDescription, Short sortOrder,
			String createdBy, Calendar updateDate, String updateBy, String description)
	{
		this.id = lookupId;
		this.category = category;
		this.codeValue = codeValue;
		this.codeDescription = codeDescription;
		this.sortOrder = sortOrder;
		this.createdBy = createdBy;
		this.updateDate = updateDate;
		this.updateBy = updateBy;
		this.description = description;
	}

	public String getCategory()
	{
		return this.category;
	}

	public void setCategory(String category)
	{
		this.category = category;
	}

	public Byte getCodeValue()
	{
		return this.codeValue;
	}

	public void setCodeValue(Byte codeValue)
	{
		this.codeValue = codeValue;
	}

	public String getCodeDescription()
	{
		return this.codeDescription;
	}

	public void setCodeDescription(String codeDescription)
	{
		this.codeDescription = codeDescription;
	}

	public Short getSortOrder()
	{
		return this.sortOrder;
	}

	public void setSortOrder(Short sortOrder)
	{
		this.sortOrder = sortOrder;
	}


}
