package gov.hhs.acf.cb.nytd.models;

// Generated May 20, 2009 10:16:43 AM by Hibernate Tools 3.2.4.GA

import java.util.Calendar;
import java.util.HashSet;
import java.util.Set;

/*
 * Message generated by hbm2java
 */
public class Message extends PersistentObject
{
    // persistent properties
	private Sender sender;	
	private String subject;
	private String messageBody;
	private SiteUser siteUser;
	private Message parentMessage;
    private Set<SiteUser> recipients;
	private Set<Message> repliedMessages = new HashSet<Message>(0);

    // transient properties
	private String messageFrom;
	private String messageAddressedTo;
	private String beforeSignatureWord;
	private String signature;	
	private String messageCreatedDate;
	
	public Message()
	{
	}

	public Message(Long messageId)
	{
		this.id = messageId;
	}

	public Message(Long messageId, String subject,
			 Calendar createdDate, String createdBy,
			Calendar updateDate, String updateBy, String description)
	{
		this.id = messageId;		
		this.subject = subject;
		this.createdDate = createdDate;
		this.createdBy = createdBy;
		this.updateDate = updateDate;
		this.updateBy = updateBy;
		this.description = description;
	}
    
	public Sender getSender()
	{
		return this.sender;
	}

	public void setSender(Sender sender)
	{
		this.sender = sender;
	}

	public String getSubject()
	{
		return this.subject;
	}

	public void setSubject(String subject)
	{
		this.subject = subject;
	}

	/**
	 * @return the messageBody
	 */
	public String getMessageBody()
	{
		return messageBody;
	}

	/**
	 * @param messageBody the messageBody to set
	 */
	public void setMessageBody(String messageBody)
	{
		this.messageBody = messageBody;
	}

	/**
	 * @return the siteUser
	 */
	public SiteUser getSiteUser()
	{
		return siteUser;
	}

	/**
	 * @param siteUser the siteUser to set
	 */
	public void setSiteUser(SiteUser siteUser)
	{
		this.siteUser = siteUser;
	}

	/**
	 * @return the parentMessage
	 */
	public Message getParentMessage()
	{
		return parentMessage;
	}

	/**
	 * @param parentMessage the parentMessage to set
	 */
	public void setParentMessage(Message parentMessage)
	{
		this.parentMessage = parentMessage;
	}

    public Set<SiteUser> getRecipients() {
        return recipients;
    }

    public void setRecipients(Set<SiteUser> recipients) {
        this.recipients = recipients;
    }

    /**
	 * @return the repliedMessages
	 */
	public Set<Message> getRepliedMessages()
	{
		return repliedMessages;
	}

	/**
	 * @param repliedMessages the repliedMessages to set
	 */
	public void setRepliedMessages(Set<Message> repliedMessages)
	{
		this.repliedMessages = repliedMessages;
	}

	/**
	 * @return the messageFrom
	 */
	public String getMessageFrom()
	{
		return messageFrom;
	}

	/**
	 * @param messageFrom the messageFrom to set
	 */
	public void setMessageFrom(String messageFrom)
	{
		this.messageFrom = messageFrom;
	}

	/**
	 * @return the signature
	 */
	public String getSignature()
	{
		return signature;
	}

	/**
	 * @param signature the signature to set
	 */
	public void setSignature(String signature)
	{
		this.signature = signature;
	}
	
	/**
	 * @return the messageCreatedDate
	 */
	public String getMessageCreatedDate()
	{
		return messageCreatedDate;
	}

	/**
	 * @param messageCreatedDate to set
	 */
	public void setMessageCreatedDate(String messageCreatedDate)
	{
		this.messageCreatedDate = messageCreatedDate;
	}

	/**
	 * @return the beforeSignatureWord
	 */
	public String getBeforeSignatureWord()
	{
		return beforeSignatureWord;
	}

	/**
	 * @param beforeSignatureWord the beforeSignatureWord to set
	 */
	public void setBeforeSignatureWord(String beforeSignatureWord)
	{
		this.beforeSignatureWord = beforeSignatureWord;
	}

	/**
	 * @return the messageAddressedTo
	 */
	public String getMessageAddressedTo()
	{
		return messageAddressedTo;
	}

	/**
	 * @param messageAddressedTo the messageAddressedTo to set
	 */
	public void setMessageAddressedTo(String messageAddressedTo)
	{
		this.messageAddressedTo = messageAddressedTo;
	}
}
