package gov.hhs.acf.cb.nytd.models;

// Generated May 20, 2009 10:16:43 AM by Hibernate Tools 3.2.4.GA

import java.util.Calendar;
import java.util.HashSet;
import java.util.Set;


/*
 * Compliance generated by hbm2java
 */
public class NonCompliance extends PersistentObject
{
	private Datum datum;
	private Transmission transmission;
	private Lookup complianceType;
	private DataAggregate dataAggregate;

	private Set<NytdError> errors = new HashSet<NytdError>(0);

	public NonCompliance()
	{
	}

	public NonCompliance(Long nonComplianceId)
	{
		this.id = nonComplianceId;
	}

	public NonCompliance(Long nonComplianceId, Datum datum,
			Transmission transmission, Lookup complianceType, DataAggregate dataAggregate,
			Calendar createdDate, String createdBy, Calendar updateDate, String updateBy,
			String description, Set<NytdError> errors)
	{
		this.id = nonComplianceId;
		this.datum = datum;
		this.transmission = transmission;
		this.createdDate = createdDate;
		this.createdBy = createdBy;
		this.updateDate = updateDate;
		this.updateBy = updateBy;
		this.description = description;
		this.errors = errors;
		this.complianceType = complianceType;
		this.dataAggregate = dataAggregate;
	}

	public Datum getDatum()
	{
		return this.datum;
	}

	public void setDatum(Datum datum)
	{
		this.datum = datum;
	}

	public Transmission getTransmission()
	{
		return this.transmission;
	}

	public void setTransmission(Transmission transmission)
	{
		this.transmission = transmission;
	}

	/**
	 * @return the errors
	 */
	public Set<NytdError> getErrors()
	{
		return errors;
	}

	/**
	 * @param errors
	 *           the errors to set
	 */
	public void setErrors(Set<NytdError> errors)
	{
		this.errors = errors;
	}

	/**
	 * @return the complianceType
	 */
	public Lookup getComplianceType()
	{
		return complianceType;
	}

	/**
	 * @param complianceType the complianceType to set
	 */
	public void setComplianceType(Lookup complianceType)
	{
		this.complianceType = complianceType;
	}

	/**
	 * @return the dataAggregate
	 */
	public DataAggregate getDataAggregate()
	{
		return dataAggregate;
	}

	/**
	 * @param dataAggregate the dataAggregate to set
	 */
	public void setDataAggregate(DataAggregate dataAggregate)
	{
		this.dataAggregate = dataAggregate;
	}

}
