package gov.hhs.acf.cb.nytd.models;

// Generated May 20, 2009 10:16:43 AM by Hibernate Tools 3.2.4.GA

import java.util.Calendar;


/*
 * NytdError originally generated by hbm2java
 * 
 * @author 18816
 */
public class NytdError extends PersistentObject {
    public static final String AGGREGATE_ERROR = "aggregateType";
    public static final String RECORD_ERROR = "recordLevel";

    protected String name;
    protected ComplianceCategory complianceCategory;
    protected ProblemDescription problemDescription;
    protected NonCompliance nonCompliance;

    // reference element id and datum value used in the
    // record error messages for internal inconsistency checks
    protected Long referenceElementId;
    protected String referenceDatumValue;

    public NytdError() {
    }

    public NytdError(Long errorid) {
        this.id = errorid;
    }

    public NytdError(Long errorId, ProblemDescription problemDescription,
                     ComplianceCategory complianceCategory, NonCompliance nonCompliance, String name, Calendar createdDate,
                     String createdBy, Calendar updateDate, String updateBy, String description) {
        this.id = errorId;
        this.problemDescription = problemDescription;
        this.complianceCategory = complianceCategory;
        this.nonCompliance = nonCompliance;
        this.name = name;
        this.createdDate = createdDate;
        this.createdBy = createdBy;
        this.updateDate = updateDate;
        this.updateBy = updateBy;
        this.description = description;
    }

    public String getName() {
        return this.name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public ComplianceCategory getComplianceCategory() {
        return this.complianceCategory;
    }

    public void setComplianceCategory(ComplianceCategory complianceCategory) {
        this.complianceCategory = complianceCategory;
    }

    public ProblemDescription getProblemDescription() {
        return this.problemDescription;
    }

    public void setProblemDescription(ProblemDescription problemDescription) {
        this.problemDescription = problemDescription;
    }

    public NonCompliance getNonCompliance() {
        return this.nonCompliance;
    }

    public void setNonCompliance(NonCompliance nonCompliance) {
        this.nonCompliance = nonCompliance;
    }

    public Long getReferenceElementId() {
        return referenceElementId;
    }

    public void setReferenceElementId(Long referenceElementId) {
        this.referenceElementId = referenceElementId;
    }

    public String getReferenceDatumValue() {
        return referenceDatumValue;
    }

    public void setReferenceDatumValue(String referenceDatumValue) {
        this.referenceDatumValue = referenceDatumValue;
    }

    public String formatErrorMessage() {
        if (problemDescription == null) {
            return "N/A";
        }

        return problemDescription.getName();
    }
}
