package gov.hhs.acf.cb.nytd.models;

import java.util.Calendar;

// Generated May 20, 2009 10:16:43 AM by Hibernate Tools 3.2.4.GA

/*
 * AggregateLevelError generated by hbm2java
 */
public class OutcomePopulation extends Population
{

	private Population population;
	private String name;
	//private String populationType;

	public OutcomePopulation()
	{
	}

	public OutcomePopulation(Long populationid)
	{
		this.id = populationid;
	}

	public OutcomePopulation(Long populationid, Population population, String name, Calendar createdDate,
			String createdBy, Calendar updateDate, String updateBy, String description)
	{
		this.id = populationid;
		this.population = population;
		this.name = name;
		this.createdDate = createdDate;
		this.createdBy = createdBy;
		this.updateDate = updateDate;
		this.updateBy = updateBy;
		this.description = description;
	}
	public String getName()
	{
		return this.name;
	}

	public void setName(String name)
	{
		this.name = name;
	}

	/**
	 * @return the population
	 */
	public Population getPopulation()
	{
		return population;
	}

	/**
	 * @param population the population to set
	 */
	public void setPopulation(Population population)
	{
		this.population = population;
	}

/*	*//**
	 * @return the populationType
	 *//*
	public String getPopulationType()
	{
		return populationType;
	}

	*//**
	 * @param populationType the populationType to set
	 *//*
	public void setPopulationType(String populationType)
	{
		this.populationType = populationType;
	}*/

}
