package gov.hhs.acf.cb.nytd.models;

// Generated May 20, 2009 10:16:43 AM by Hibernate Tools 3.2.4.GA

import java.util.Calendar;
import java.util.HashSet;
import java.util.Set;

/*
 * Population generated by hbm2java
 */
public class Population extends PersistentObject
{
	private String name;
	private String populationType;

	private Set<ElementPopulation> elementPopulations = new HashSet<ElementPopulation>(0);
	private Set<AllowedValue> allowedValues = new HashSet<AllowedValue>(0);

	public Population()
	{
	}

	public Population(Long populationid)
	{
		this.id = populationid;
	}

	public Population(Long populationId, String name, Calendar createdDate, String createdBy,
			Calendar updateDate, String updateBy, String description, 
			Set<ElementPopulation> elementPopulations, Set<AllowedValue> allowedValues)
	{
		this.id = populationId;
		this.name = name;
		this.createdDate = createdDate;
		this.createdBy = createdBy;
		this.updateDate = updateDate;
		this.updateBy = updateBy;
		this.description = description;
		this.elementPopulations = elementPopulations;
		this.allowedValues = allowedValues;
	}

	public String getName()
	{
		return this.name;
	}

	public void setName(String name)
	{
		this.name = name;
	}

	public Set<ElementPopulation> getElementPopulations()
	{
		return this.elementPopulations;
	}

	public void setElementPopulations(Set<ElementPopulation> elementPopulations)
	{
		this.elementPopulations = elementPopulations;
	}

	public Set<AllowedValue> getAllowedValues()
	{
		return this.allowedValues;
	}

	public void setAllowedValues(Set<AllowedValue> allowedValues)
	{
		this.allowedValues = allowedValues;
	}
	/**
	 * @return the populationType
	 */
	public String getPopulationType()
	{
		return populationType;
	}

	/**
	 * @param populationType the populationType to set
	 */
	public void setPopulationType(String populationType)
	{
		this.populationType = populationType;
	}

}
