package gov.hhs.acf.cb.nytd.models;

// Generated May 20, 2009 10:16:43 AM by Hibernate Tools 3.2.4.GA

import java.util.Calendar;
import java.util.HashSet;
import java.util.Set;

/*
 * Privilege generated by hbm2java
 */
public class Privilege extends PersistentObject
{
	private String privilegeType;

	private Set<DerivedRole> derivedRoles = new HashSet<DerivedRole>(0);

	public Privilege()
	{
	}

	public Privilege(Long privilegeId)
	{
		this.id = privilegeId;
	}

	public Privilege(Long privilegeId, String privilegeType, Calendar createdDate, String createdBy,
			Calendar updateDate, String updateBy, String description,
			Set<DerivedRole> derivedRoles)
	{
		this.id = privilegeId;
		this.privilegeType = privilegeType;
		this.createdDate = createdDate;
		this.createdBy = createdBy;
		this.updateDate = updateDate;
		this.updateBy = updateBy;
		this.description = description;
		this.derivedRoles = derivedRoles;
	}

	public String getPrivilegeType()
	{
		return this.privilegeType;
	}

	public void setPrivilegeType(String privilegeType)
	{
		this.privilegeType = privilegeType;
	}

	public Set<DerivedRole> getDerivedRoles()
	{
		return this.derivedRoles;
	}

	public void setDerivedRoles(Set<DerivedRole> derivedRoles)
	{
		this.derivedRoles = derivedRoles;
	}


}
