package gov.hhs.acf.cb.nytd.models;

// Generated May 20, 2009 10:16:43 AM by Hibernate Tools 3.2.4.GA

import java.util.Calendar;
import java.util.HashSet;
import java.util.Set;

/*
 * Region generated by hbm2java
 */
public class Region extends PersistentObject
{
	private String region;
	private String regionCode;

	private Set<State> states = new HashSet<State>(0);

	public Region()
	{
	}

	public Region(Long regionId)
	{
		this.id = regionId;
	}

	public Region(Long regionId, String region, String regionCode, Calendar createdDate, String createdBy,
			Calendar updateDate, String updateBy, String description, Set<State> states)
	{
		this.id = regionId;
		this.region = region;
		this.regionCode = regionCode;
		this.createdDate = createdDate;
		this.createdBy = createdBy;
		this.updateDate = updateDate;
		this.updateBy = updateBy;
		this.description = description;
		this.states = states;
	}

	public String getRegion()
	{
		return this.region;
	}

	public void setRegion(String region)
	{
		this.region = region;
	}

	public String getRegionCode()
	{
		return this.regionCode;
	}

	public void setRegionCode(String regionCode)
	{
		this.regionCode = regionCode;
	}

	public Set<State> getStates()
	{
		return this.states;
	}

	public void setStates(Set<State> states)
	{
		this.states = states;
	}

    public String toString() {
        return "Region: "+region;
    }
}
