package gov.hhs.acf.cb.nytd.models;

// Generated May 20, 2009 10:16:43 AM by Hibernate Tools 3.2.4.GA

import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import java.util.HashSet;
import java.util.Set;

/*
 * ReportingPeriod generated by hbm2java
 */
public class ReportingPeriod extends PersistentObject
{
	private String name;
	private Calendar startReportingDate;
	private Calendar endReportingDate;
	private Integer outcomeAge;
	private Set<DueDate> dueDates = new HashSet<DueDate>(0);
	private Set<Transmission> transmissions = new HashSet<Transmission>(0);
	private String endRptDateStr;
	private String startRptDateStr;
	private String correctedFileEndRptDateStr;

	public ReportingPeriod()
	{
	}

	public ReportingPeriod(Long reportingPeriodId)
	{
		this.id = reportingPeriodId;
	}

	public ReportingPeriod(Long reportingPeriodId, String name, Calendar startReportingDate,
			Calendar endReportingDate, Calendar createdDate, String createdBy, Calendar updateDate,
			String updateBy, String description, Set<DueDate> dueDates, Set<Transmission> transmissions,String endRptDateStr,String startRptDateStr)
	{
		this.id = reportingPeriodId;
		this.name = name;
		this.startReportingDate = startReportingDate;
		this.endReportingDate = endReportingDate;
		this.createdDate = createdDate;
		this.createdBy = createdBy;
		this.updateDate = updateDate;
		this.updateBy = updateBy;
		this.description = description;
		this.dueDates = dueDates;
		this.transmissions = transmissions;
		this.endRptDateStr = endRptDateStr;
		this.startRptDateStr = startRptDateStr; 
	}

	public String getName()
	{
		return this.name;
	}

	public void setName(String name)
	{
		this.name = name;
	}

	public Calendar getStartReportingDate()
	{
		return this.startReportingDate;
	}

	public void setStartReportingDate(Calendar startReportingDate)
	{
		this.startReportingDate = startReportingDate;
		DateFormat dateFormat = new SimpleDateFormat("MMMMM dd, yyyy");
		setStartRptDateStr(dateFormat.format(startReportingDate.getTime()));
	}

	public Calendar getEndReportingDate()
	{
		return this.endReportingDate;
	}

	public void setEndReportingDate(Calendar endReportingDate)
	{
		Calendar tempCal = Calendar.getInstance();
		this.endReportingDate = endReportingDate;
		DateFormat dateFormat = new SimpleDateFormat("MMMMM dd, yyyy");
		setEndRptDateStr(dateFormat.format(endReportingDate.getTime()));
		tempCal.setTime(endReportingDate.getTime());
		tempCal.add(Calendar.MONTH, 6);
		tempCal.set(Calendar.DAY_OF_MONTH, tempCal.getActualMaximum(Calendar.DAY_OF_MONTH));
		setCorrectedFileEndRptDateStr(dateFormat.format(tempCal.getTime()));
		
	}

	public Integer getOutcomeAge()
	{
		return this.outcomeAge;
	}

	public void setOutcomeAge(Integer outcomeAge)
	{
		this.outcomeAge = outcomeAge;
	}

	public Set<DueDate> getDueDates()
	{
		return this.dueDates;
	}

	public void setDueDates(Set<DueDate> dueDates)
	{
		this.dueDates = dueDates;
	}

	public Set<Transmission> getTransmissions()
	{
		return this.transmissions;
	}

	public void setTransmissions(Set<Transmission> transmissions)
	{
		this.transmissions = transmissions;
	}
	/**
	 * @return the endRptDateStr
	 */
	public String getEndRptDateStr()
	{
		return endRptDateStr;
	}

	/**
	 * @param endRptDateStr the endRptDateStr to set
	 */
	public void setEndRptDateStr(String endRptDateStr)
	{
		this.endRptDateStr = endRptDateStr;
	}

	/**
	 * @return the startRptDateStr
	 */
	public String getStartRptDateStr()
	{
		return startRptDateStr;
	}

	/**
	 * @param startRptDateStr the startRptDateStr to set
	 */
	public void setStartRptDateStr(String startRptDateStr)
	{
		this.startRptDateStr = startRptDateStr;
	}

	/**
	 * @return the correctedFileEndRptDateStr
	 */
	public String getCorrectedFileEndRptDateStr() {
		return correctedFileEndRptDateStr;
	}

	/**
	 * @param correctedFileEndRptDateStr the correctedFileEndRptDateStr to set
	 */
	private void setCorrectedFileEndRptDateStr(String correctedFileEndRptDateStr) {
		this.correctedFileEndRptDateStr = correctedFileEndRptDateStr;
	}

}
