package gov.hhs.acf.cb.nytd.models;

// Generated May 20, 2009 10:16:43 AM by Hibernate Tools 3.2.4.GA

import java.util.HashSet;
import java.util.Set;

/*
 * SecondaryUserRole generated by hbm2java
 */
public class SecondaryUserRole extends PersistentObject
{
	private String name;

	private Set<DerivedRole> derivedRoles = new HashSet<DerivedRole>(0);
	private Set<SiteUserSecondaryUserRole> siteUserSecondaryUserRoles = new HashSet<SiteUserSecondaryUserRole>(0);
	
	public interface Client {
		public String getName();
		public Set<DerivedRole> getDerivedRoles();
		public Set<SiteUserSecondaryUserRole> getSiteUserSecondaryUserRoles();
	}

	public SecondaryUserRole()
	{
	}

	public SecondaryUserRole(Long secondaryUserRoleId)
	{
		this.id = secondaryUserRoleId;
	}

	public String getName()
	{
		return this.name;
	}

	public void setName(String name)
	{
		this.name = name;
	}

	public Set<DerivedRole> getDerivedRoles()
	{
		return this.derivedRoles;
	}

	public void setDerivedRoles(Set<DerivedRole> derivedRoles)
	{
		this.derivedRoles = derivedRoles;
	}

	public Set<SiteUserSecondaryUserRole> getSiteUserSecondaryUserRoles()
	{
		return siteUserSecondaryUserRoles;
	}

	private void setSiteUserSecondaryUserRoles(Set<SiteUserSecondaryUserRole> siteUserSecondaryUserRoles)
	{
		this.siteUserSecondaryUserRoles = siteUserSecondaryUserRoles;
	}
}
