package gov.hhs.acf.cb.nytd.models;

// Generated Aug 13, 2013 11:55:42 AM by Hibernate Tools 3.4.0.CR1

import gov.hhs.acf.cb.nytd.models.helper.BarChartBar;
import lombok.Getter;
import lombok.Setter;

import java.util.ArrayList;
import java.util.Calendar;
import java.util.List;

/**
 * Statereportservicetypes generated by hbm2java
 */
public class Statereportservicetypes implements java.io.Serializable {

	private long statereportid;
	private Statereport statereport;
	private long e20count;
	private double e20percent;
	private String e20percentstr;
	private long e21count;
	private double e21percent;
	private String e21percentstr;
	private long e22count;
	private double e22percent;
	private String e22percentstr;
	private long e23count;
	private double e23percent;
	private String e23percentstr;
	private long e24count;
	private double e24percent;
	private String e24percentstr;
	private long e25count;
	private double e25percent;
	private String e25percentstr;
	private long e26count;
	private double e26percent;
	private String e26percentstr;
	private long e27count;
	private double e27percent;
	private String e27percentstr;
	private long e28count;
	private double e28percent;
	private String e28percentstr;
	private long e29count;
	private double e29percent;
	private String e29percentstr;
	private long e30count;
	private double e30percent;
	private String e30percentstr;
	private long e31count;
	private double e31percent;
	private String e31percentstr;
	private long e32count;
	private double e32percent;
	private String e32percentstr;
	private long e33count;
	private double e33percent;
	private String e33percentstr;
	private Calendar createdate;
	@Getter @Setter private List<BarChartBar> barchartBars;

	public Statereportservicetypes() {
	}
	
	public void populateBarChart()
	{
		barchartBars = new ArrayList<BarChartBar>();
		
		barchartBars.add(new BarChartBar("Independent living needs assessment",e20percent));
		barchartBars.add(new BarChartBar("Academic support",e21percent));
		barchartBars.add(new BarChartBar("Post-secondary educational support",e22percent));
		barchartBars.add(new BarChartBar("Career preparation",e23percent));
		barchartBars.add(new BarChartBar("Employment programs or vocational training",e24percent));
		barchartBars.add(new BarChartBar("Budget and financial management",e25percent));
		barchartBars.add(new BarChartBar("Housing education and home management training",e26percent));
		barchartBars.add(new BarChartBar("Health education and risk prevention",e27percent));
		barchartBars.add(new BarChartBar("Family support and healthy marriage education",e28percent));
		barchartBars.add(new BarChartBar("Mentoring",e29percent));
		barchartBars.add(new BarChartBar("Supervised independent living",e30percent));
		barchartBars.add(new BarChartBar("Room and board financial assistance",e31percent));
		barchartBars.add(new BarChartBar("Education financial assistance",e32percent));
		barchartBars.add(new BarChartBar("Other financial assistance",e33percent));
	}

	public Statereportservicetypes(Statereport statereport) {
		this.statereport = statereport;
	}

	public Statereportservicetypes(Statereport statereport, long e20count,
			double e20percent, String e20percentstr, long e21count,
			double e21percent, String e21percentstr, long e22count,
			double e22percent, String e22percentstr, long e23count,
			double e23percent, String e23percentstr, long e24count,
			double e24percent, String e24percentstr, long e25count,
			double e25percent, String e25percentstr, long e26count,
			double e26percent, String e26percentstr, long e27count,
			double e27percent, String e27percentstr, long e28count,
			double e28percent, String e28percentstr, long e29count,
			double e29percent, String e29percentstr, long e30count,
			double e30percent, String e30percentstr, long e31count,
			double e31percent, String e31percentstr, long e32count,
			double e32percent, String e32percentstr, long e33count,
			double e33percent, String e33percentstr, Calendar createdate) {
		this.statereport = statereport;
		this.e20count = e20count;
		this.e20percent = e20percent;
		this.e20percentstr = e20percentstr;
		this.e21count = e21count;
		this.e21percent = e21percent;
		this.e21percentstr = e21percentstr;
		this.e22count = e22count;
		this.e22percent = e22percent;
		this.e22percentstr = e22percentstr;
		this.e23count = e23count;
		this.e23percent = e23percent;
		this.e23percentstr = e23percentstr;
		this.e24count = e24count;
		this.e24percent = e24percent;
		this.e24percentstr = e24percentstr;
		this.e25count = e25count;
		this.e25percent = e25percent;
		this.e25percentstr = e25percentstr;
		this.e26count = e26count;
		this.e26percent = e26percent;
		this.e26percentstr = e26percentstr;
		this.e27count = e27count;
		this.e27percent = e27percent;
		this.e27percentstr = e27percentstr;
		this.e28count = e28count;
		this.e28percent = e28percent;
		this.e28percentstr = e28percentstr;
		this.e29count = e29count;
		this.e29percent = e29percent;
		this.e29percentstr = e29percentstr;
		this.e30count = e30count;
		this.e30percent = e30percent;
		this.e30percentstr = e30percentstr;
		this.e31count = e31count;
		this.e31percent = e31percent;
		this.e31percentstr = e31percentstr;
		this.e32count = e32count;
		this.e32percent = e32percent;
		this.e32percentstr = e32percentstr;
		this.e33count = e33count;
		this.e33percent = e33percent;
		this.e33percentstr = e33percentstr;
		this.createdate = createdate;
	}

	public long getStatereportid() {
		return this.statereportid;
	}

	public void setStatereportid(long statereportid) {
		this.statereportid = statereportid;
	}

	public Statereport getStatereport() {
		return this.statereport;
	}

	public void setStatereport(Statereport statereport) {
		this.statereport = statereport;
	}

	public long getE20count() {
		return this.e20count;
	}

	public void setE20count(long e20count) {
		this.e20count = e20count;
	}

	public double getE20percent() {
		return this.e20percent;
	}

	public void setE20percent(double e20percent) {
		this.e20percent = e20percent;
	}

	public String getE20percentstr() {
		return this.e20percentstr;
	}

	public void setE20percentstr(String e20percentstr) {
		this.e20percentstr = e20percentstr;
	}

	public long getE21count() {
		return this.e21count;
	}

	public void setE21count(long e21count) {
		this.e21count = e21count;
	}

	public double getE21percent() {
		return this.e21percent;
	}

	public void setE21percent(double e21percent) {
		this.e21percent = e21percent;
	}

	public String getE21percentstr() {
		return this.e21percentstr;
	}

	public void setE21percentstr(String e21percentstr) {
		this.e21percentstr = e21percentstr;
	}

	public long getE22count() {
		return this.e22count;
	}

	public void setE22count(long e22count) {
		this.e22count = e22count;
	}

	public double getE22percent() {
		return this.e22percent;
	}

	public void setE22percent(double e22percent) {
		this.e22percent = e22percent;
	}

	public String getE22percentstr() {
		return this.e22percentstr;
	}

	public void setE22percentstr(String e22percentstr) {
		this.e22percentstr = e22percentstr;
	}

	public long getE23count() {
		return this.e23count;
	}

	public void setE23count(long e23count) {
		this.e23count = e23count;
	}

	public double getE23percent() {
		return this.e23percent;
	}

	public void setE23percent(double e23percent) {
		this.e23percent = e23percent;
	}

	public String getE23percentstr() {
		return this.e23percentstr;
	}

	public void setE23percentstr(String e23percentstr) {
		this.e23percentstr = e23percentstr;
	}

	public long getE24count() {
		return this.e24count;
	}

	public void setE24count(long e24count) {
		this.e24count = e24count;
	}

	public double getE24percent() {
		return this.e24percent;
	}

	public void setE24percent(double e24percent) {
		this.e24percent = e24percent;
	}

	public String getE24percentstr() {
		return this.e24percentstr;
	}

	public void setE24percentstr(String e24percentstr) {
		this.e24percentstr = e24percentstr;
	}

	public long getE25count() {
		return this.e25count;
	}

	public void setE25count(long e25count) {
		this.e25count = e25count;
	}

	public double getE25percent() {
		return this.e25percent;
	}

	public void setE25percent(double e25percent) {
		this.e25percent = e25percent;
	}

	public String getE25percentstr() {
		return this.e25percentstr;
	}

	public void setE25percentstr(String e25percentstr) {
		this.e25percentstr = e25percentstr;
	}

	public long getE26count() {
		return this.e26count;
	}

	public void setE26count(long e26count) {
		this.e26count = e26count;
	}

	public double getE26percent() {
		return this.e26percent;
	}

	public void setE26percent(double e26percent) {
		this.e26percent = e26percent;
	}

	public String getE26percentstr() {
		return this.e26percentstr;
	}

	public void setE26percentstr(String e26percentstr) {
		this.e26percentstr = e26percentstr;
	}

	public long getE27count() {
		return this.e27count;
	}

	public void setE27count(long e27count) {
		this.e27count = e27count;
	}

	public double getE27percent() {
		return this.e27percent;
	}

	public void setE27percent(double e27percent) {
		this.e27percent = e27percent;
	}

	public String getE27percentstr() {
		return this.e27percentstr;
	}

	public void setE27percentstr(String e27percentstr) {
		this.e27percentstr = e27percentstr;
	}

	public long getE28count() {
		return this.e28count;
	}

	public void setE28count(long e28count) {
		this.e28count = e28count;
	}

	public double getE28percent() {
		return this.e28percent;
	}

	public void setE28percent(double e28percent) {
		this.e28percent = e28percent;
	}

	public String getE28percentstr() {
		return this.e28percentstr;
	}

	public void setE28percentstr(String e28percentstr) {
		this.e28percentstr = e28percentstr;
	}

	public long getE29count() {
		return this.e29count;
	}

	public void setE29count(long e29count) {
		this.e29count = e29count;
	}

	public double getE29percent() {
		return this.e29percent;
	}

	public void setE29percent(double e29percent) {
		this.e29percent = e29percent;
	}

	public String getE29percentstr() {
		return this.e29percentstr;
	}

	public void setE29percentstr(String e29percentstr) {
		this.e29percentstr = e29percentstr;
	}

	public long getE30count() {
		return this.e30count;
	}

	public void setE30count(long e30count) {
		this.e30count = e30count;
	}

	public double getE30percent() {
		return this.e30percent;
	}

	public void setE30percent(double e30percent) {
		this.e30percent = e30percent;
	}

	public String getE30percentstr() {
		return this.e30percentstr;
	}

	public void setE30percentstr(String e30percentstr) {
		this.e30percentstr = e30percentstr;
	}

	public long getE31count() {
		return this.e31count;
	}

	public void setE31count(long e31count) {
		this.e31count = e31count;
	}

	public double getE31percent() {
		return this.e31percent;
	}

	public void setE31percent(double e31percent) {
		this.e31percent = e31percent;
	}

	public String getE31percentstr() {
		return this.e31percentstr;
	}

	public void setE31percentstr(String e31percentstr) {
		this.e31percentstr = e31percentstr;
	}

	public long getE32count() {
		return this.e32count;
	}

	public void setE32count(long e32count) {
		this.e32count = e32count;
	}

	public double getE32percent() {
		return this.e32percent;
	}

	public void setE32percent(double e32percent) {
		this.e32percent = e32percent;
	}

	public String getE32percentstr() {
		return this.e32percentstr;
	}

	public void setE32percentstr(String e32percentstr) {
		this.e32percentstr = e32percentstr;
	}

	public long getE33count() {
		return this.e33count;
	}

	public void setE33count(long e33count) {
		this.e33count = e33count;
	}

	public double getE33percent() {
		return this.e33percent;
	}

	public void setE33percent(double e33percent) {
		this.e33percent = e33percent;
	}

	public String getE33percentstr() {
		return this.e33percentstr;
	}

	public void setE33percentstr(String e33percentstr) {
		this.e33percentstr = e33percentstr;
	}

	public Calendar getCreatedate() {
		return this.createdate;
	}

	public void setCreatedate(Calendar createdate) {
		this.createdate = createdate;
	}

}
