package gov.hhs.acf.cb.nytd.models;

// Generated Aug 13, 2013 11:55:42 AM by Hibernate Tools 3.4.0.CR1

import gov.hhs.acf.cb.nytd.models.helper.SDPOutcomesHeaderData;
import gov.hhs.acf.cb.nytd.models.helper.SDPServedHeaderData;
import lombok.Getter;
import lombok.Setter;

import java.util.Calendar;

/**
 * Statereport generated by hbm2java
 */
public class Statereport implements java.io.Serializable {

	private long statereportid;
	private long stateid;
	private String rpyear;
	private String reportingperiod;
	private String populationtype;
	private long totalythcount;
	private long servedythcount;
	private double minage;
	private double maxage;
	private double meanage;
	private Calendar createdate;
	@Getter @Setter private String surveyratestr;
	@Getter @Setter private long avgdaystosurvey;
	@Getter @Setter private String pctsurveyedontime;
	private Statereportreasonnonparti statereportreasonnonparti;
	private Statereporteduleveldetail statereporteduleveldetail;
	private Statereportservicetypes statereportservicetypes;
	private Statereportoutcomes statereportoutcomes;
	private Statereportdemographics statereportdemographics;
	private Statereportservicesreceived statereportservicesreceived;
	@Getter @Setter private Vwsdpfollowupdemographics vwsdpfollowupdemographics;
	@Getter @Setter private Vwsdpoutcomes vwsdpoutcomes;
	@Getter @Setter private String reportPeriod;
	@Getter @Setter private String reportPeriodLong;
	@Getter @Setter private String stateName;
	@Getter @Setter private SDPServedHeaderData servedHeaderData;
	@Getter @Setter private SDPOutcomesHeaderData outcomesHeaderData;
	@Getter @Setter private Vwsdpfollowupnonpartreasons vwsdpfollowupnonpartreasons;
	@Getter @Setter long totalCohortYouth;
	@Getter @Setter long totalCohortYouthReported;
	@Getter @Setter long totalSampledYouth;
	@Getter @Setter long totalSampledYouthReported;
	@Getter @Setter long youthInFosterCare;
	@Getter @Setter long youthOutFosterCare;
	@Getter @Setter String fosterCareParticipationRate;
	@Getter @Setter String dischargedParticipationRate;
	@Getter @Setter String outcomesReceivedServicesRate;
	
	public Statereport() {
	}

	public Statereport(long statereportid) {
		this.statereportid = statereportid;
	}

	public Statereport(long statereportid, long stateid, String rpyear,
			String reportingperiod, String populationtype, long totalythcount,
			long servedythcount, double minage, double maxage, double meanage,
			Calendar createdate,
			Statereportreasonnonparti statereportreasonnonparti,
			Statereporteduleveldetail statereporteduleveldetail,
			Statereportservicetypes statereportservicetypes,
			Statereportoutcomes statereportoutcomes,
			Statereportdemographics statereportdemographics,
			Statereportservicesreceived statereportservicesreceived,
			Vwsdpfollowupdemographics vwsdpfollowupdemographics,
			long totalCohortYouth,long totalCohortYouthReported,
			long totalSampledYouth, long totalSampledYouthReported, long youthInFosterCare,long youthOutFosterCare,String fosterCareParticipationRate,
			String dischargedParticipationRate,String outcomesReceivedServicesRate,
			String surveyratestr,long avgdaystosurvey,String pctsurveyedontime) {
		this.statereportid = statereportid;
		this.stateid = stateid;
		this.rpyear = rpyear;
		this.reportingperiod = reportingperiod;
		this.populationtype = populationtype;
		this.totalythcount = totalythcount;
		this.servedythcount = servedythcount;
		this.minage = minage;
		this.maxage = maxage;
		this.meanage = meanage;
		this.createdate = createdate;
		this.statereportreasonnonparti = statereportreasonnonparti;
		this.statereporteduleveldetail = statereporteduleveldetail;
		this.statereportservicetypes = statereportservicetypes;
		this.statereportoutcomes = statereportoutcomes;
		this.statereportdemographics = statereportdemographics;
		this.statereportservicesreceived = statereportservicesreceived;
		this.vwsdpfollowupdemographics = vwsdpfollowupdemographics;
		this.totalCohortYouth = totalCohortYouth;
		this.totalCohortYouthReported = totalCohortYouthReported;
		this.youthInFosterCare = youthInFosterCare;
		this.youthOutFosterCare = youthOutFosterCare;
		this.fosterCareParticipationRate = fosterCareParticipationRate;
		this.dischargedParticipationRate = dischargedParticipationRate;
		this.outcomesReceivedServicesRate = outcomesReceivedServicesRate;
		this.surveyratestr = surveyratestr;
		this.avgdaystosurvey = avgdaystosurvey;
		this.pctsurveyedontime =pctsurveyedontime;
		this.totalSampledYouth = totalSampledYouth;
		this.totalSampledYouthReported = totalSampledYouthReported;
	}

	public long getStatereportid() {
		return this.statereportid;
	}

	public void setStatereportid(long statereportid) {
		this.statereportid = statereportid;
	}

	public long getStateid() {
		return this.stateid;
	}

	public void setStateid(long stateid) {
		this.stateid = stateid;
	}

	public String getRpyear() {
		return this.rpyear;
	}

	public void setRpyear(String rpyear) {
		this.rpyear = rpyear;
	}

	public String getReportingperiod() {
		return this.reportingperiod;
	}

	public void setReportingperiod(String reportingperiod) {
		this.reportingperiod = reportingperiod;
	}

	public String getPopulationtype() {
		return this.populationtype;
	}

	public void setPopulationtype(String populationtype) {
		this.populationtype = populationtype;
	}

	public long getTotalythcount() {
		return this.totalythcount;
	}

	public void setTotalythcount(long totalythcount) {
		this.totalythcount = totalythcount;
	}

	public long getServedythcount() {
		return this.servedythcount;
	}

	public void setServedythcount(long servedythcount) {
		this.servedythcount = servedythcount;
	}

	public double getMinage() {
		return this.minage;
	}

	public void setMinage(double minage) {
		this.minage = minage;
	}

	public double getMaxage() {
		return this.maxage;
	}

	public void setMaxage(double maxage) {
		this.maxage = maxage;
	}

	public double getMeanage() {
		return this.meanage;
	}

	public void setMeanage(double meanage) {
		this.meanage = meanage;
	}

	public Calendar getCreatedate() {
		return this.createdate;
	}

	public void setCreatedate(Calendar createdate) {
		this.createdate = createdate;
	}

	public Statereportreasonnonparti getStatereportreasonnonparti() {
		return this.statereportreasonnonparti;
	}

	public void setStatereportreasonnonparti(
			Statereportreasonnonparti statereportreasonnonparti) {
		this.statereportreasonnonparti = statereportreasonnonparti;
	}

	public Statereporteduleveldetail getStatereporteduleveldetail() {
		return this.statereporteduleveldetail;
	}

	public void setStatereporteduleveldetail(
			Statereporteduleveldetail statereporteduleveldetail) {
		this.statereporteduleveldetail = statereporteduleveldetail;
	}

	public Statereportservicetypes getStatereportservicetypes() {
		return this.statereportservicetypes;
	}

	public void setStatereportservicetypes(
			Statereportservicetypes statereportservicetypes) {
		this.statereportservicetypes = statereportservicetypes;
	}

	public Statereportoutcomes getStatereportoutcomes() {
		return this.statereportoutcomes;
	}

	public void setStatereportoutcomes(Statereportoutcomes statereportoutcomes) {
		this.statereportoutcomes = statereportoutcomes;
	}

	public Statereportdemographics getStatereportdemographics() {
		return this.statereportdemographics;
	}

	public void setStatereportdemographics(
			Statereportdemographics statereportdemographics) {
		this.statereportdemographics = statereportdemographics;
	}

	public Statereportservicesreceived getStatereportservicesreceived() {
		return this.statereportservicesreceived;
	}

	public void setStatereportservicesreceived(
			Statereportservicesreceived statereportservicesreceived) {
		this.statereportservicesreceived = statereportservicesreceived;
	}

}
