package gov.hhs.acf.cb.nytd.models;

// Generated Aug 13, 2013 11:55:42 AM by Hibernate Tools 3.4.0.CR1

import gov.hhs.acf.cb.nytd.models.helper.PieChartPie;
import lombok.Getter;
import lombok.Setter;

import java.util.ArrayList;
import java.util.Calendar;
import java.util.List;

/**
 * Statereportservicesreceived generated by hbm2java
 */
public class Statereportservicesreceived implements java.io.Serializable {

	private long statereportid;
	private Statereport statereport;
	private String zeropercentstr;
	private double zeropercent;
	private long zerocount;
	private String onetwopercentstr;
	private double onetwopercent;
	private long onetwocount;
	private String threefourpercentstr;
	private double threefourpercent;
	private long threefourcount;
	private String fivemorepercentstr;
	private double fivemorepercent;
	private long fivemorecount;
	private Calendar createdate;
	@Getter @Setter private List<PieChartPie> piechartPies;
	
	
	public void populatePieChart()
	{
		piechartPies = new ArrayList<PieChartPie>();
		
		piechartPies.add(new PieChartPie("0",zeropercent));
		piechartPies.add(new PieChartPie("1 or 2",onetwopercent));
		piechartPies.add(new PieChartPie("3 or 4",threefourpercent));
		piechartPies.add(new PieChartPie("5 or more",fivemorepercent));
		
		/*piechartPies.add(new PieChartPie("0",0.0D));
		piechartPies.add(new PieChartPie("1 or 2",25.5D));
		piechartPies.add(new PieChartPie("3 or 4",24.5D));
		piechartPies.add(new PieChartPie("5 or more",50.00D));*/
		
	}

	public Statereportservicesreceived() {
	}

	public Statereportservicesreceived(Statereport statereport) {
		this.statereport = statereport;
	}

	public Statereportservicesreceived(Statereport statereport,
			String zeropercentstr, double zeropercent, long zerocount,
			String onetwopercentstr, double onetwopercent, long onetwocount,
			String threefourpercentstr, double threefourpercent,
			long threefourcount, String fivemorepercentstr,
			double fivemorepercent, long fivemorecount, Calendar createdate) {
		this.statereport = statereport;
		this.zeropercentstr = zeropercentstr;
		this.zeropercent = zeropercent;
		this.zerocount = zerocount;
		this.onetwopercentstr = onetwopercentstr;
		this.onetwopercent = onetwopercent;
		this.onetwocount = onetwocount;
		this.threefourpercentstr = threefourpercentstr;
		this.threefourpercent = threefourpercent;
		this.threefourcount = threefourcount;
		this.fivemorepercentstr = fivemorepercentstr;
		this.fivemorepercent = fivemorepercent;
		this.fivemorecount = fivemorecount;
		this.createdate = createdate;
	}

	public long getStatereportid() {
		return this.statereportid;
	}

	public void setStatereportid(long statereportid) {
		this.statereportid = statereportid;
	}

	public Statereport getStatereport() {
		return this.statereport;
	}

	public void setStatereport(Statereport statereport) {
		this.statereport = statereport;
	}

	public String getZeropercentstr() {
		return this.zeropercentstr;
	}

	public void setZeropercentstr(String zeropercentstr) {
		this.zeropercentstr = zeropercentstr;
	}

	public double getZeropercent() {
		return this.zeropercent;
	}

	public void setZeropercent(double zeropercent) {
		this.zeropercent = zeropercent;
	}

	public long getZerocount() {
		return this.zerocount;
	}

	public void setZerocount(long zerocount) {
		this.zerocount = zerocount;
	}

	public String getOnetwopercentstr() {
		return this.onetwopercentstr;
	}

	public void setOnetwopercentstr(String onetwopercentstr) {
		this.onetwopercentstr = onetwopercentstr;
	}

	public double getOnetwopercent() {
		return this.onetwopercent;
	}

	public void setOnetwopercent(double onetwopercent) {
		this.onetwopercent = onetwopercent;
	}

	public long getOnetwocount() {
		return this.onetwocount;
	}

	public void setOnetwocount(long onetwocount) {
		this.onetwocount = onetwocount;
	}

	public String getThreefourpercentstr() {
		return this.threefourpercentstr;
	}

	public void setThreefourpercentstr(String threefourpercentstr) {
		this.threefourpercentstr = threefourpercentstr;
	}

	public double getThreefourpercent() {
		return this.threefourpercent;
	}

	public void setThreefourpercent(double threefourpercent) {
		this.threefourpercent = threefourpercent;
	}

	public long getThreefourcount() {
		return this.threefourcount;
	}

	public void setThreefourcount(long threefourcount) {
		this.threefourcount = threefourcount;
	}

	public String getFivemorepercentstr() {
		return this.fivemorepercentstr;
	}

	public void setFivemorepercentstr(String fivemorepercentstr) {
		this.fivemorepercentstr = fivemorepercentstr;
	}

	public double getFivemorepercent() {
		return this.fivemorepercent;
	}

	public void setFivemorepercent(double fivemorepercent) {
		this.fivemorepercent = fivemorepercent;
	}

	public long getFivemorecount() {
		return this.fivemorecount;
	}

	public void setFivemorecount(long fivemorecount) {
		this.fivemorecount = fivemorecount;
	}

	public Calendar getCreatedate() {
		return this.createdate;
	}

	public void setCreatedate(Calendar createdate) {
		this.createdate = createdate;
	}

}
