package gov.hhs.acf.cb.nytd.models;

// Generated May 20, 2009 10:16:43 AM by Hibernate Tools 3.2.4.GA

import java.util.Calendar;
import java.util.HashSet;
import java.util.Set;

/*
 * State generated by hbm2java
 */
public class State extends PersistentObject
{
	private Region region;
	private String stateName;
	private String abbreviation;
	private String fipsCode;

	private Set<PrimaryUserRole> primaryUserRoles = new HashSet<PrimaryUserRole>(0);
	private Set<Transmission> transmissions  = new HashSet<Transmission>(0);

	public State()
	{
	}
	
	public State(Long stateId)
	{
		this.id = stateId;
	}

	public State(Region region, String stateName, String abbreviation, String fipsCode,
			Calendar createdDate, String createdBy, Calendar updateDate, String updateBy, String description,
			Set<PrimaryUserRole> primaryUserRoles, Set<Transmission> transmissions)
	{
		this.region = region;
		this.stateName = stateName;
		this.abbreviation = abbreviation;
		this.fipsCode = fipsCode;
		this.createdDate = createdDate;
		this.createdBy = createdBy;
		this.updateDate = updateDate;
		this.updateBy = updateBy;
		this.description = description;
		this.primaryUserRoles = primaryUserRoles;
		this.transmissions = transmissions;
	}

	public Region getRegion()
	{
		return this.region;
	}

	public void setRegion(Region region)
	{
		this.region = region;
	}

	public String getStateName()
	{
		return this.stateName;
	}

	public void setStateName(String stateName)
	{
		this.stateName = stateName;
	}

	public String getAbbreviation()
	{
		return this.abbreviation;
	}

	public void setAbbreviation(String abbreviation)
	{
		this.abbreviation = abbreviation;
	}

	public String getFipsCode()
	{
		return this.fipsCode;
	}

	public void setFipsCode(String fipsCode)
	{
		this.fipsCode = fipsCode;
	}

	/**
	 * @return the transmissions
	 */
	public Set<Transmission> getTransmissions()
	{
		return transmissions;
	}

	/**
	 * @param transmissions the transmissions to set
	 */
	public void setTransmissions(Set<Transmission> transmissions)
	{
		this.transmissions = transmissions;
	}

    public String toString() {
        return "State: "+stateName;
    }
}
