package gov.hhs.acf.cb.nytd.models;

// Generated Aug 26, 2013 3:29:01 PM by Hibernate Tools 3.4.0.CR1

import gov.hhs.acf.cb.nytd.models.helper.SDPTextChartRow;
import lombok.Getter;
import lombok.Setter;

import java.util.ArrayList;
import java.util.Calendar;
import java.util.List;

/**
 * Statereportoutcomes generated by hbm2java
 */
public class Statereportoutcomes implements java.io.Serializable {

	private long id;
	private Statereport statereport;
	private String employed;
	private String receivingtraining;
	private String receivingsspay;
	private String receivingeduaid;
	private String receivingothsupt;
	private String receivingpubfin;
	private String receivingpubfood;
	private String receivingpubhous;
	private String attendingschool;
	private String completedhsorged;
	private String receivinglicense;
	private String receivingdegree;
	private String sabusereferral;
	private String incarcerated;
	private String havingchildren;
	private String homeless;
	private String connectiontoadult;
	private String havingmedicaid;
	private String healthinsurance;
	private String fostercaretype;
	private Calendar createdate;
	@Getter @Setter private List<SDPTextChartRow> financialOutcomes;
	@Getter @Setter private List<SDPTextChartRow> educationalOutcomes;
	@Getter @Setter private List<SDPTextChartRow> behaviorOutcomes;
	@Getter @Setter private List<SDPTextChartRow> homelessOutcomes;
	@Getter @Setter private List<SDPTextChartRow> connectionOutcomes;
	@Getter @Setter private List<SDPTextChartRow> insuranceOutcomes;

	public Statereportoutcomes() {
	}

	public Statereportoutcomes(long id) {
		this.id = id;
	}

	public Statereportoutcomes(long id, Statereport statereport,
			String employed, String receivingtraining, String receivingsspay,
			String receivingeduaid, String receivingothsupt,
			String receivingpubfin, String receivingpubfood,
			String receivingpubhous, String attendingschool,
			String completedhsorged, String receivinglicense,
			String receivingdegree, String sabusereferral, String incarcerated,
			String havingchildren, String homeless, String connectiontoadult,
			String havingmedicaid, String healthinsurance,
			String fostercaretype, Calendar createdate) {
		this.id = id;
		this.statereport = statereport;
		this.employed = employed;
		this.receivingtraining = receivingtraining;
		this.receivingsspay = receivingsspay;
		this.receivingeduaid = receivingeduaid;
		this.receivingothsupt = receivingothsupt;
		this.receivingpubfin = receivingpubfin;
		this.receivingpubfood = receivingpubfood;
		this.receivingpubhous = receivingpubhous;
		this.attendingschool = attendingschool;
		this.completedhsorged = completedhsorged;
		this.receivinglicense = receivinglicense;
		this.receivingdegree = receivingdegree;
		this.sabusereferral = sabusereferral;
		this.incarcerated = incarcerated;
		this.havingchildren = havingchildren;
		this.homeless = homeless;
		this.connectiontoadult = connectiontoadult;
		this.havingmedicaid = havingmedicaid;
		this.healthinsurance = healthinsurance;
		this.fostercaretype = fostercaretype;
		this.createdate = createdate;
	}

	public long getId() {
		return this.id;
	}

	public void setId(long id) {
		this.id = id;
	}

	public Statereport getStatereport() {
		return this.statereport;
	}

	public void setStatereport(Statereport statereport) {
		this.statereport = statereport;
	}

	public String getEmployed() {
		return this.employed;
	}

	public void setEmployed(String employed) {
		this.employed = employed;
	}

	public String getReceivingtraining() {
		return this.receivingtraining;
	}

	public void setReceivingtraining(String receivingtraining) {
		this.receivingtraining = receivingtraining;
	}

	public String getReceivingsspay() {
		return this.receivingsspay;
	}

	public void setReceivingsspay(String receivingsspay) {
		this.receivingsspay = receivingsspay;
	}

	public String getReceivingeduaid() {
		return this.receivingeduaid;
	}

	public void setReceivingeduaid(String receivingeduaid) {
		this.receivingeduaid = receivingeduaid;
	}

	public String getReceivingothsupt() {
		return this.receivingothsupt;
	}

	public void setReceivingothsupt(String receivingothsupt) {
		this.receivingothsupt = receivingothsupt;
	}

	public String getReceivingpubfin() {
		return this.receivingpubfin;
	}

	public void setReceivingpubfin(String receivingpubfin) {
		this.receivingpubfin = receivingpubfin;
	}

	public String getReceivingpubfood() {
		return this.receivingpubfood;
	}

	public void setReceivingpubfood(String receivingpubfood) {
		this.receivingpubfood = receivingpubfood;
	}

	public String getReceivingpubhous() {
		return this.receivingpubhous;
	}

	public void setReceivingpubhous(String receivingpubhous) {
		this.receivingpubhous = receivingpubhous;
	}

	public String getAttendingschool() {
		return this.attendingschool;
	}

	public void setAttendingschool(String attendingschool) {
		this.attendingschool = attendingschool;
	}

	public String getCompletedhsorged() {
		return this.completedhsorged;
	}

	public void setCompletedhsorged(String completedhsorged) {
		this.completedhsorged = completedhsorged;
	}

	public String getReceivinglicense() {
		return this.receivinglicense;
	}

	public void setReceivinglicense(String receivinglicense) {
		this.receivinglicense = receivinglicense;
	}

	public String getReceivingdegree() {
		return this.receivingdegree;
	}

	public void setReceivingdegree(String receivingdegree) {
		this.receivingdegree = receivingdegree;
	}

	public String getSabusereferral() {
		return this.sabusereferral;
	}

	public void setSabusereferral(String sabusereferral) {
		this.sabusereferral = sabusereferral;
	}

	public String getIncarcerated() {
		return this.incarcerated;
	}

	public void setIncarcerated(String incarcerated) {
		this.incarcerated = incarcerated;
	}

	public String getHavingchildren() {
		return this.havingchildren;
	}

	public void setHavingchildren(String havingchildren) {
		this.havingchildren = havingchildren;
	}

	public String getHomeless() {
		return this.homeless;
	}

	public void setHomeless(String homeless) {
		this.homeless = homeless;
	}

	public String getConnectiontoadult() {
		return this.connectiontoadult;
	}

	public void setConnectiontoadult(String connectiontoadult) {
		this.connectiontoadult = connectiontoadult;
	}

	public String getHavingmedicaid() {
		return this.havingmedicaid;
	}

	public void setHavingmedicaid(String havingmedicaid) {
		this.havingmedicaid = havingmedicaid;
	}

	public String getHealthinsurance() {
		return this.healthinsurance;
	}

	public void setHealthinsurance(String healthinsurance) {
		this.healthinsurance = healthinsurance;
	}

	public String getFostercaretype() {
		return this.fostercaretype;
	}

	public void setFostercaretype(String fostercaretype) {
		this.fostercaretype = fostercaretype;
	}

	public Calendar getCreatedate() {
		return this.createdate;
	}

	public void setCreatedate(Calendar createdate) {
		this.createdate = createdate;
	}
	
	public void generateOutcomesChart()
	{
		financialOutcomes =  new ArrayList<SDPTextChartRow>();
		financialOutcomes.add(new SDPTextChartRow("Reported current part-time or full-time employment", employed));
		financialOutcomes.add(new SDPTextChartRow("Reported receiving employment-related training in the past year", receivingtraining));
//		financialOutcomes.add(new SDPTextChartRow("Reported receiving social security payments", receivingsspay));
//		financialOutcomes.add(new SDPTextChartRow("Reported receiving financial aid for educational expenses", receivingeduaid));
//		financialOutcomes.add(new SDPTextChartRow("Reported receiving financial support from another source", receivingothsupt));
//		financialOutcomes.add(new SDPTextChartRow("Reported receiving public financial assistance<sup>*</sup>", receivingpubfin));
//		financialOutcomes.add(new SDPTextChartRow("Reported receiving public food assistance<sup>*</sup>", receivingpubfood));
//		financialOutcomes.add(new SDPTextChartRow("Reported receiving public housing assistance<sup>*</sup>", receivingpubhous));
		
		educationalOutcomes = new ArrayList<SDPTextChartRow>();
		educationalOutcomes.add(new SDPTextChartRow("Reported being enrolled and attending school",attendingschool));
		educationalOutcomes.add(new SDPTextChartRow("Reported having completed high school or GED",completedhsorged));
//		educationalOutcomes.add(new SDPTextChartRow("Reported receiving vocational license or certificate",receivinglicense));
//		educationalOutcomes.add(new SDPTextChartRow("Reported receiving a college degree(e.g., Associate, Bachelor, or higher degree)",receivingdegree));
		
		
		behaviorOutcomes = new ArrayList<SDPTextChartRow>();
		behaviorOutcomes.add(new SDPTextChartRow("Reported ever receiving a substance abuse referral",sabusereferral));
		behaviorOutcomes.add(new SDPTextChartRow("Reported ever having been incarcerated",incarcerated));
		behaviorOutcomes.add(new SDPTextChartRow("Reported ever having children",havingchildren));
		
		homelessOutcomes =  new ArrayList<SDPTextChartRow>();
		homelessOutcomes.add(new SDPTextChartRow("Reported ever having been homeless",homeless));
		
		connectionOutcomes =  new ArrayList<SDPTextChartRow>();
		connectionOutcomes.add(new SDPTextChartRow("Reported having a current positive connection to an adult",connectiontoadult));
		
		insuranceOutcomes =  new ArrayList<SDPTextChartRow>(); 
		insuranceOutcomes.add(new SDPTextChartRow("Reported having Medicaid",havingmedicaid));
		insuranceOutcomes.add(new SDPTextChartRow("Reported having some other type of health insurance",healthinsurance));
		
		
	}

}
