package gov.hhs.acf.cb.nytd.models;

// Generated Aug 13, 2013 11:55:42 AM by Hibernate Tools 3.4.0.CR1

import gov.hhs.acf.cb.nytd.models.helper.SDPTextChartRow;
import lombok.Getter;
import lombok.Setter;

import java.util.ArrayList;
import java.util.Calendar;
import java.util.List;

/**
 * Statereportreasonnonparti generated by hbm2java
 */
public class Statereportreasonnonparti implements java.io.Serializable {

	private long statereportid;
	private Statereport statereport;
	private String youthdeclined;
	private String parentdeclined;
	private String incapacitated;
	private String incarcerated;
	private String runawaymissing;
	private String unablelocate;
	private String death;
	private Calendar createdate;
	@Getter @Setter private List<SDPTextChartRow> nonParticipationReasons;
	@Getter @Setter private String notInSample;

	public Statereportreasonnonparti() {
	}

	public Statereportreasonnonparti(Statereport statereport) {
		this.statereport = statereport;
	}

	public Statereportreasonnonparti(Statereport statereport,
			String youthdeclined, String parentdeclined, String incapacitated,
			String incarcerated, String runawaymissing, String unablelocate,
			String notInSample,
			String death, Calendar createdate) {
		this.statereport = statereport;
		this.youthdeclined = youthdeclined;
		this.parentdeclined = parentdeclined;
		this.incapacitated = incapacitated;
		this.incarcerated = incarcerated;
		this.runawaymissing = runawaymissing;
		this.unablelocate = unablelocate;
		this.death = death;
		this.createdate = createdate;
		this.notInSample = notInSample;
	}

	public long getStatereportid() {
		return this.statereportid;
	}

	public void setStatereportid(long statereportid) {
		this.statereportid = statereportid;
	}

	public Statereport getStatereport() {
		return this.statereport;
	}

	public void setStatereport(Statereport statereport) {
		this.statereport = statereport;
	}

	public String getYouthdeclined() {
		return this.youthdeclined;
	}

	public void setYouthdeclined(String youthdeclined) {
		this.youthdeclined = youthdeclined;
	}

	public String getParentdeclined() {
		return this.parentdeclined;
	}

	public void setParentdeclined(String parentdeclined) {
		this.parentdeclined = parentdeclined;
	}

	public String getIncapacitated() {
		return this.incapacitated;
	}

	public void setIncapacitated(String incapacitated) {
		this.incapacitated = incapacitated;
	}

	public String getIncarcerated() {
		return this.incarcerated;
	}

	public void setIncarcerated(String incarcerated) {
		this.incarcerated = incarcerated;
	}

	public String getRunawaymissing() {
		return this.runawaymissing;
	}

	public void setRunawaymissing(String runawaymissing) {
		this.runawaymissing = runawaymissing;
	}

	public String getUnablelocate() {
		return this.unablelocate;
	}

	public void setUnablelocate(String unablelocate) {
		this.unablelocate = unablelocate;
	}

	public String getDeath() {
		return this.death;
	}

	public void setDeath(String death) {
		this.death = death;
	}

	public Calendar getCreatedate() {
		return this.createdate;
	}

	public void setCreatedate(Calendar createdate) {
		this.createdate = createdate;
	}
	public void generateNonParticipationReasonsChart()
	{
		nonParticipationReasons = new ArrayList<SDPTextChartRow>();
		nonParticipationReasons.add(new SDPTextChartRow("Youth declined", youthdeclined));
		nonParticipationReasons.add(new SDPTextChartRow("Parent declined", parentdeclined));
		nonParticipationReasons.add(new SDPTextChartRow("Incapacitated", incapacitated));
		nonParticipationReasons.add(new SDPTextChartRow("Incarcerated", incarcerated));
		nonParticipationReasons.add(new SDPTextChartRow("Runaway or missing", runawaymissing));
		nonParticipationReasons.add(new SDPTextChartRow("Unable to locate/invite", unablelocate));
		nonParticipationReasons.add(new SDPTextChartRow("Death", death));
	//	nonParticipationReasons.add(new SDPTextChartRow("Not in sample", notInSample));
		
		
	}

}
