package gov.hhs.acf.cb.nytd.models;

// Generated Aug 13, 2013 11:55:42 AM by Hibernate Tools 3.4.0.CR1

import gov.hhs.acf.cb.nytd.models.helper.BarChartBar;
import lombok.Getter;
import lombok.Setter;

import java.util.ArrayList;
import java.util.Calendar;
import java.util.List;

/**
 * Statereporteduleveldetail generated by hbm2java
 */
public class Statereporteduleveldetail implements java.io.Serializable {

	private long statereportid;
	private Statereport statereport;
	private String undersixstr;
	private double undersix;
	private double undersixavgage;
	private String sixstr;
	private double six;
	private double sixavgage;
	private String sevenstr;
	private double seven;
	private double sevenavgage;
	private String eightstr;
	private double eight;
	private double eightavgage;
	private String ninestr;
	private double nine;
	private double nineavgage;
	private String tenstr;
	private double ten;
	private double tenavgage;
	private String elevenstr;
	private double eleven;
	private double elevenavgage;
	private String twelvestr;
	private double twelve;
	private double twelveavgage;
	private String postsecstr;
	private double postsec;
	private double postsecavgage;
	private String collegestr;
	private double college;
	private double collegeavgage;
	private String blankstr;
	private double blank;
	private double blankavgage;
	private String outrangestr;
	private double outrange;
	private double outrangeavgage;
	private Calendar createdate;
	@Getter @Setter private List<BarChartBar> barchartBars;

	public Statereporteduleveldetail() {
	}

	public Statereporteduleveldetail(Statereport statereport) {
		this.statereport = statereport;
	}

	public void populateBarChart()
	{
		barchartBars = new ArrayList<BarChartBar>();
		
		barchartBars.add(new BarChartBar("Under 6th grade (age "+(int)undersixavgage+")",undersix));
		barchartBars.add(new BarChartBar("6th grade (age "+(int)sixavgage+")",six));
		barchartBars.add(new BarChartBar("7th grade (age "+(int)sevenavgage+")",seven));
		barchartBars.add(new BarChartBar("8th grade (age "+(int)eightavgage+")",eight));
		barchartBars.add(new BarChartBar("9th grade (age "+(int)nineavgage+")",nine));
		barchartBars.add(new BarChartBar("10th grade (age "+(int)tenavgage+")",ten));
		barchartBars.add(new BarChartBar("11th grade (age "+(int)elevenavgage+")",eleven));
		barchartBars.add(new BarChartBar("12th grade (age "+(int)twelveavgage+")",twelve));
		barchartBars.add(new BarChartBar("Post secondary education or training (age "+(int)postsecavgage+")",postsec));
		barchartBars.add(new BarChartBar("College (age "+(int)collegeavgage+")",college));
		barchartBars.add(new BarChartBar("Blank (age "+(int)blankavgage+")",blank));
	}
	
	public Statereporteduleveldetail(Statereport statereport,
			String undersixstr, double undersix, double undersixavgage,
			String sixstr, double six, double sixavgage, String sevenstr,
			double seven, double sevenavgage, String eightstr, double eight,
			double eightavgage, String ninestr, double nine, double nineavgage,
			String tenstr, double ten, double tenavgage, String elevenstr,
			double eleven, double elevenavgage, String twelvestr,
			double twelve, double twelveavgage, String postsecstr,
			double postsec, double postsecavgage, String collegestr,
			double college, double collegeavgage, String blankstr,
			double blank, double blankavgage, String outrangestr,
			double outrange, double outrangeavgage, Calendar createdate) {
		this.statereport = statereport;
		this.undersixstr = undersixstr;
		this.undersix = undersix;
		this.undersixavgage = undersixavgage;
		this.sixstr = sixstr;
		this.six = six;
		this.sixavgage = sixavgage;
		this.sevenstr = sevenstr;
		this.seven = seven;
		this.sevenavgage = sevenavgage;
		this.eightstr = eightstr;
		this.eight = eight;
		this.eightavgage = eightavgage;
		this.ninestr = ninestr;
		this.nine = nine;
		this.nineavgage = nineavgage;
		this.tenstr = tenstr;
		this.ten = ten;
		this.tenavgage = tenavgage;
		this.elevenstr = elevenstr;
		this.eleven = eleven;
		this.elevenavgage = elevenavgage;
		this.twelvestr = twelvestr;
		this.twelve = twelve;
		this.twelveavgage = twelveavgage;
		this.postsecstr = postsecstr;
		this.postsec = postsec;
		this.postsecavgage = postsecavgage;
		this.collegestr = collegestr;
		this.college = college;
		this.collegeavgage = collegeavgage;
		this.blankstr = blankstr;
		this.blank = blank;
		this.blankavgage = blankavgage;
		this.outrangestr = outrangestr;
		this.outrange = outrange;
		this.outrangeavgage = outrangeavgage;
		this.createdate = createdate;
	}

	public long getStatereportid() {
		return this.statereportid;
	}

	public void setStatereportid(long statereportid) {
		this.statereportid = statereportid;
	}

	public Statereport getStatereport() {
		return this.statereport;
	}

	public void setStatereport(Statereport statereport) {
		this.statereport = statereport;
	}

	public String getUndersixstr() {
		return this.undersixstr;
	}

	public void setUndersixstr(String undersixstr) {
		this.undersixstr = undersixstr;
	}

	public double getUndersix() {
		return this.undersix;
	}

	public void setUndersix(double undersix) {
		this.undersix = undersix;
	}

	public double getUndersixavgage() {
		return this.undersixavgage;
	}

	public void setUndersixavgage(double undersixavgage) {
		this.undersixavgage = undersixavgage;
	}

	public String getSixstr() {
		return this.sixstr;
	}

	public void setSixstr(String sixstr) {
		this.sixstr = sixstr;
	}

	public double getSix() {
		return this.six;
	}

	public void setSix(double six) {
		this.six = six;
	}

	public double getSixavgage() {
		return this.sixavgage;
	}

	public void setSixavgage(double sixavgage) {
		this.sixavgage = sixavgage;
	}

	public String getSevenstr() {
		return this.sevenstr;
	}

	public void setSevenstr(String sevenstr) {
		this.sevenstr = sevenstr;
	}

	public double getSeven() {
		return this.seven;
	}

	public void setSeven(double seven) {
		this.seven = seven;
	}

	public double getSevenavgage() {
		return this.sevenavgage;
	}

	public void setSevenavgage(double sevenavgage) {
		this.sevenavgage = sevenavgage;
	}

	public String getEightstr() {
		return this.eightstr;
	}

	public void setEightstr(String eightstr) {
		this.eightstr = eightstr;
	}

	public double getEight() {
		return this.eight;
	}

	public void setEight(double eight) {
		this.eight = eight;
	}

	public double getEightavgage() {
		return this.eightavgage;
	}

	public void setEightavgage(double eightavgage) {
		this.eightavgage = eightavgage;
	}

	public String getNinestr() {
		return this.ninestr;
	}

	public void setNinestr(String ninestr) {
		this.ninestr = ninestr;
	}

	public double getNine() {
		return this.nine;
	}

	public void setNine(double nine) {
		this.nine = nine;
	}

	public double getNineavgage() {
		return this.nineavgage;
	}

	public void setNineavgage(double nineavgage) {
		this.nineavgage = nineavgage;
	}

	public String getTenstr() {
		return this.tenstr;
	}

	public void setTenstr(String tenstr) {
		this.tenstr = tenstr;
	}

	public double getTen() {
		return this.ten;
	}

	public void setTen(double ten) {
		this.ten = ten;
	}

	public double getTenavgage() {
		return this.tenavgage;
	}

	public void setTenavgage(double tenavgage) {
		this.tenavgage = tenavgage;
	}

	public String getElevenstr() {
		return this.elevenstr;
	}

	public void setElevenstr(String elevenstr) {
		this.elevenstr = elevenstr;
	}

	public double getEleven() {
		return this.eleven;
	}

	public void setEleven(double eleven) {
		this.eleven = eleven;
	}

	public double getElevenavgage() {
		return this.elevenavgage;
	}

	public void setElevenavgage(double elevenavgage) {
		this.elevenavgage = elevenavgage;
	}

	public String getTwelvestr() {
		return this.twelvestr;
	}

	public void setTwelvestr(String twelvestr) {
		this.twelvestr = twelvestr;
	}

	public double getTwelve() {
		return this.twelve;
	}

	public void setTwelve(double twelve) {
		this.twelve = twelve;
	}

	public double getTwelveavgage() {
		return this.twelveavgage;
	}

	public void setTwelveavgage(double twelveavgage) {
		this.twelveavgage = twelveavgage;
	}

	public String getPostsecstr() {
		return this.postsecstr;
	}

	public void setPostsecstr(String postsecstr) {
		this.postsecstr = postsecstr;
	}

	public double getPostsec() {
		return this.postsec;
	}

	public void setPostsec(double postsec) {
		this.postsec = postsec;
	}

	public double getPostsecavgage() {
		return this.postsecavgage;
	}

	public void setPostsecavgage(double postsecavgage) {
		this.postsecavgage = postsecavgage;
	}

	public String getCollegestr() {
		return this.collegestr;
	}

	public void setCollegestr(String collegestr) {
		this.collegestr = collegestr;
	}

	public double getCollege() {
		return this.college;
	}

	public void setCollege(double college) {
		this.college = college;
	}

	public double getCollegeavgage() {
		return this.collegeavgage;
	}

	public void setCollegeavgage(double collegeavgage) {
		this.collegeavgage = collegeavgage;
	}

	public String getBlankstr() {
		return this.blankstr;
	}

	public void setBlankstr(String blankstr) {
		this.blankstr = blankstr;
	}

	public double getBlank() {
		return this.blank;
	}

	public void setBlank(double blank) {
		this.blank = blank;
	}

	public double getBlankavgage() {
		return this.blankavgage;
	}

	public void setBlankavgage(double blankavgage) {
		this.blankavgage = blankavgage;
	}

	public String getOutrangestr() {
		return this.outrangestr;
	}

	public void setOutrangestr(String outrangestr) {
		this.outrangestr = outrangestr;
	}

	public double getOutrange() {
		return this.outrange;
	}

	public void setOutrange(double outrange) {
		this.outrange = outrange;
	}

	public double getOutrangeavgage() {
		return this.outrangeavgage;
	}

	public void setOutrangeavgage(double outrangeavgage) {
		this.outrangeavgage = outrangeavgage;
	}

	public Calendar getCreatedate() {
		return this.createdate;
	}

	public void setCreatedate(Calendar createdate) {
		this.createdate = createdate;
	}

}
