package gov.hhs.acf.cb.nytd.models;

// Generated Aug 13, 2013 11:55:42 AM by Hibernate Tools 3.4.0.CR1

import gov.hhs.acf.cb.nytd.models.helper.SDPTextChartRow;
import lombok.Getter;
import lombok.Setter;

import java.util.ArrayList;
import java.util.Calendar;
import java.util.List;

/**
 * Statereportdemographics generated by hbm2java
 */
public class Statereportdemographics implements java.io.Serializable {

	private long statereportid;
	private Statereport statereport;
	private String malestr;
	private double male;
	private String femalestr;
	private double female;
	private String whitestr;
	private double white;
	private String blackstr;
	private double black;
	private String amindstr;
	private double amind;
	private String asianstr;
	private double asian;
	private String hawaiianstr;
	private double hawaiian;
	private String unknownstr;
	private double unknown;
	private String hispanicstr;
	private double hispanic;
	private String declinedstr;
	private double declined;
	private String fostercarestr;
	private double fostercare;
	private String tribestr;
	private double tribe;
	private String deliquentstr;
	private double deliquent;
	private String espedustr;
	private double espedu;
	@Getter @Setter private String receivedservstr;
	@Getter @Setter private double receivedserv;
	@Getter @Setter private String fostercaretype;
	private Calendar createdate;
	@Getter @Setter private List<SDPTextChartRow> sex;
	@Getter @Setter private List<SDPTextChartRow> ethnicity;
	@Getter @Setter private List<SDPTextChartRow> services;

	public Statereportdemographics() {
	}

	public Statereportdemographics(Statereport statereport) {
		this.statereport = statereport;
	}

	public Statereportdemographics(Statereport statereport, String malestr,
			double male, String femalestr, double female, String whitestr,
			double white, String blackstr, double black, String amindstr,
			double amind, String asianstr, double asian, String hawaiianstr,
			double hawaiian, String unknownstr, double unknown,
			String hispanicstr, double hispanic, String declinedstr,
			double declined, String fostercarestr, double fostercare,
			String tribestr, double tribe, String deliquentstr,
			double deliquent, String espedustr, double espedu,String receivedservstr, double receivedserv,
			String fostercaretype,Calendar createdate) {
		this.statereport = statereport;
		this.malestr = malestr;
		this.male = male;
		this.femalestr = femalestr;
		this.female = female;
		this.whitestr = whitestr;
		this.white = white;
		this.blackstr = blackstr;
		this.black = black;
		this.amindstr = amindstr;
		this.amind = amind;
		this.asianstr = asianstr;
		this.asian = asian;
		this.hawaiianstr = hawaiianstr;
		this.hawaiian = hawaiian;
		this.unknownstr = unknownstr;
		this.unknown = unknown;
		this.hispanicstr = hispanicstr;
		this.hispanic = hispanic;
		this.declinedstr = declinedstr;
		this.declined = declined;
		this.fostercarestr = fostercarestr;
		this.fostercare = fostercare;
		this.tribestr = tribestr;
		this.tribe = tribe;
		this.deliquentstr = deliquentstr;
		this.deliquent = deliquent;
		this.espedustr = espedustr;
		this.espedu = espedu;
		this.receivedservstr = receivedservstr;
		this.receivedserv = receivedserv;
		this.fostercaretype = fostercaretype;
		this.createdate = createdate;
	}

	public long getStatereportid() {
		return this.statereportid;
	}

	public void setStatereportid(long statereportid) {
		this.statereportid = statereportid;
	}

	public Statereport getStatereport() {
		return this.statereport;
	}

	public void setStatereport(Statereport statereport) {
		this.statereport = statereport;
	}

	public String getMalestr() {
		return this.malestr;
	}

	public void setMalestr(String malestr) {
		this.malestr = malestr;
	}

	public double getMale() {
		return this.male;
	}

	public void setMale(double male) {
		this.male = male;
	}

	public String getFemalestr() {
		return this.femalestr;
	}

	public void setFemalestr(String femalestr) {
		this.femalestr = femalestr;
	}

	public double getFemale() {
		return this.female;
	}

	public void setFemale(double female) {
		this.female = female;
	}

	public String getWhitestr() {
		return this.whitestr;
	}

	public void setWhitestr(String whitestr) {
		this.whitestr = whitestr;
	}

	public double getWhite() {
		return this.white;
	}

	public void setWhite(double white) {
		this.white = white;
	}

	public String getBlackstr() {
		return this.blackstr;
	}

	public void setBlackstr(String blackstr) {
		this.blackstr = blackstr;
	}

	public double getBlack() {
		return this.black;
	}

	public void setBlack(double black) {
		this.black = black;
	}

	public String getAmindstr() {
		return this.amindstr;
	}

	public void setAmindstr(String amindstr) {
		this.amindstr = amindstr;
	}

	public double getAmind() {
		return this.amind;
	}

	public void setAmind(double amind) {
		this.amind = amind;
	}

	public String getAsianstr() {
		return this.asianstr;
	}

	public void setAsianstr(String asianstr) {
		this.asianstr = asianstr;
	}

	public double getAsian() {
		return this.asian;
	}

	public void setAsian(double asian) {
		this.asian = asian;
	}

	public String getHawaiianstr() {
		return this.hawaiianstr;
	}

	public void setHawaiianstr(String hawaiianstr) {
		this.hawaiianstr = hawaiianstr;
	}

	public double getHawaiian() {
		return this.hawaiian;
	}

	public void setHawaiian(double hawaiian) {
		this.hawaiian = hawaiian;
	}

	public String getUnknownstr() {
		return this.unknownstr;
	}

	public void setUnknownstr(String unknownstr) {
		this.unknownstr = unknownstr;
	}

	public double getUnknown() {
		return this.unknown;
	}

	public void setUnknown(double unknown) {
		this.unknown = unknown;
	}

	public String getHispanicstr() {
		return this.hispanicstr;
	}

	public void setHispanicstr(String hispanicstr) {
		this.hispanicstr = hispanicstr;
	}

	public double getHispanic() {
		return this.hispanic;
	}

	public void setHispanic(double hispanic) {
		this.hispanic = hispanic;
	}

	public String getDeclinedstr() {
		return this.declinedstr;
	}

	public void setDeclinedstr(String declinedstr) {
		this.declinedstr = declinedstr;
	}

	public double getDeclined() {
		return this.declined;
	}

	public void setDeclined(double declined) {
		this.declined = declined;
	}

	public String getFostercarestr() {
		return this.fostercarestr;
	}

	public void setFostercarestr(String fostercarestr) {
		this.fostercarestr = fostercarestr;
	}

	public double getFostercare() {
		return this.fostercare;
	}

	public void setFostercare(double fostercare) {
		this.fostercare = fostercare;
	}

	public String getTribestr() {
		return this.tribestr;
	}

	public void setTribestr(String tribestr) {
		this.tribestr = tribestr;
	}

	public double getTribe() {
		return this.tribe;
	}

	public void setTribe(double tribe) {
		this.tribe = tribe;
	}

	public String getDeliquentstr() {
		return this.deliquentstr;
	}

	public void setDeliquentstr(String deliquentstr) {
		this.deliquentstr = deliquentstr;
	}

	public double getDeliquent() {
		return this.deliquent;
	}

	public void setDeliquent(double deliquent) {
		this.deliquent = deliquent;
	}

	public String getEspedustr() {
		return this.espedustr;
	}

	public void setEspedustr(String espedustr) {
		this.espedustr = espedustr;
	}

	public double getEspedu() {
		return this.espedu;
	}

	public void setEspedu(double espedu) {
		this.espedu = espedu;
	}

	public Calendar getCreatedate() {
		return this.createdate;
	}

	public void setCreatedate(Calendar createdate) {
		this.createdate = createdate;
	}
	
	public void generateSDPDemographicChart()
	{
		sex = new ArrayList<SDPTextChartRow>();
		sex.add(new SDPTextChartRow("Male", malestr));
		sex.add(new SDPTextChartRow("Female", femalestr));
		
		ethnicity = new ArrayList<SDPTextChartRow>();
		ethnicity.add(new SDPTextChartRow("American Indian or Alaska Native",amindstr));
		ethnicity.add(new SDPTextChartRow("Asian",asianstr));
		ethnicity.add(new SDPTextChartRow("Black or African American",blackstr));
		ethnicity.add(new SDPTextChartRow("Native Hawaiian or Other Pacific Islander",hawaiianstr));
		ethnicity.add(new SDPTextChartRow("White",whitestr));
		ethnicity.add(new SDPTextChartRow("Unknown or Declined",unknownstr));
		ethnicity.add(new SDPTextChartRow("Hispanic or Latino ethnicity<sup>*</sup>",hispanicstr));
		
		services = new ArrayList<SDPTextChartRow>();
		services.add(new SDPTextChartRow("<b>Receiving Services</b>",receivedservstr));
	}

}
