package gov.hhs.acf.cb.nytd.models;

// Generated May 20, 2009 10:16:43 AM by Hibernate Tools 3.2.4.GA

import java.util.Calendar;
import java.util.HashSet;
import java.util.Set;

/*
 * TransmissionRecord generated by hbm2java
 */
public class TransmissionRecord extends PersistentObject
{	
	private Transmission transmission;
	private String name;
	private String recordNumber;
	private String notes;
	private ServedPopulation servedPopulation;
	private OutcomePopulation outcomePopulation;

	private Set<Datum> datums = new HashSet<Datum>(0);

	public TransmissionRecord()
	{
	}

	public TransmissionRecord(Long transmissionRecordId)
	{
		this.id = transmissionRecordId;
	}

	public TransmissionRecord(Long transmissionRecordId, String name, String recordNumber, Calendar createdDate, String createdBy, Calendar updateDate,
			String updateBy, String description, Set<Datum> datums)
	{
		this.id = transmissionRecordId;
		this.name = name;
		this.recordNumber = recordNumber;
		this.createdDate = createdDate;
		this.createdBy = createdBy;
		this.updateDate = updateDate;
		this.updateBy = updateBy;
		this.description = description;
		this.datums = datums;
	}

	public String getName()
	{
		return this.name;
	}

	public void setName(String name)
	{
		this.name = name;
	}

	public String getRecordNumber()
	{
		return this.recordNumber;
	}

	public void setRecordNumber(String recordNumber)
	{
		this.recordNumber = recordNumber;
	}

	public Set<Datum> getDatums()
	{
		return this.datums;
	}

	public void setDatums(Set<Datum> datums)
	{
		this.datums = datums;
	}

	/**
	 * @return the notes
	 */
	public String getNotes()
	{
		return notes;
	}

	/**
	 * @param notes
	 *           the notes to set
	 */
	public void setNotes(String notes)
	{
		this.notes = notes;
	}

	/**
	 * @return the servedPopulation
	 */
	public ServedPopulation getServedPopulation()
	{
		return servedPopulation;
	}

	/**
	 * @param servedPopulation the servedPopulation to set
	 */
	public void setServedPopulation(ServedPopulation servedPopulation)
	{
		this.servedPopulation = servedPopulation;
	}

	/**
	 * @return the outcomePopulation
	 */
	public OutcomePopulation getOutcomePopulation()
	{
		return outcomePopulation;
	}

	/**
	 * @param outcomePopulation the outcomePopulation to set
	 */
	public void setOutcomePopulation(OutcomePopulation outcomePopulation)
	{
		this.outcomePopulation = outcomePopulation;
	}

	/**
	 * @return the transmission
	 */
	public Transmission getTransmission()
	{
		return transmission;
	}

	/**
	 * @param transmission the transmission to set
	 */
	public void setTransmission(Transmission transmission)
	{
		this.transmission = transmission;
	}

}
