package gov.hhs.acf.cb.nytd.models;

import java.util.Calendar;

// Generated Jun 1, 2009 2:40:24 PM by Hibernate Tools 3.2.4.GA

/*
 * Notes generated by hbm2java
 */
public class TransmissionNote extends PersistentObject
{

	private Long transmissionNoteId;
	private Transmission transmission;
	private String note;

	public TransmissionNote()
	{
	}

	public TransmissionNote(Long noteId)
	{
		this.transmissionNoteId = noteId;
	}

	public TransmissionNote(Long transmissionNoteId, Transmission transmission, String note, Calendar createddate,
			String createdby, Calendar updatedate, String updateby, String description)
	{
		this.transmissionNoteId = transmissionNoteId;
		this.transmission = transmission;
		this.note = note;
	}

	public Long getTransmissionNoteId()
	{
		return this.transmissionNoteId;
	}

	public void setTransmissionNoteId(Long transmissionNoteId)
	{
		this.transmissionNoteId = transmissionNoteId;
	}

	public Transmission getTransmission()
	{
		return this.transmission;
	}

	public void setTransmission(Transmission transmission)
	{
		this.transmission = transmission;
	}

	public String getNote()
	{
		return this.note;
	}

	public void setNote(String notes)
	{
		this.note = notes;
	}

}
