package gov.hhs.acf.cb.nytd.models;

// Generated May 20, 2009 10:16:43 AM by Hibernate Tools 3.2.4.GA

import java.util.Calendar;
import java.util.HashSet;
import java.util.Set;

/*
 * TransmissionType generated by hbm2java
 */
public class TransmissionType extends PersistentObject
{
	private String name;

	private Set<Transmission> transmissions = new HashSet<Transmission>(0);
	private Set<DueDate> dueDates = new HashSet<DueDate>(0);

	public TransmissionType()
	{
	}

	public TransmissionType(Long transmissionTypeId)
	{
		this.id = transmissionTypeId;
	}

	public TransmissionType(Long transmissionTypeId, String name, Calendar createdDate, String createdBy,
			Calendar updateDate, String updateBy, String description, Set<Transmission> transmissions,
			Set<DueDate> dueDates)
	{
		this.id = transmissionTypeId;
		this.name = name;
		this.createdDate = createdDate;
		this.createdBy = createdBy;
		this.updateDate = updateDate;
		this.updateBy = updateBy;
		this.description = description;
		this.transmissions = transmissions;
		this.dueDates = dueDates;
	}

	public String getName()
	{
		return this.name;
	}

	public void setName(String name)
	{
		this.name = name;
	}

	public Set<Transmission> getTransmissions()
	{
		return this.transmissions;
	}

	public void setTransmissions(Set<Transmission> transmissions)
	{
		this.transmissions = transmissions;
	}

	public Set<DueDate> getDueDates()
	{
		return this.dueDates;
	}

	public void setDueDates(Set<DueDate> dueDates)
	{
		this.dueDates = dueDates;
	}

}
