package gov.hhs.acf.cb.nytd.models;

import gov.hhs.acf.cb.nytd.models.helper.SDPTextChartRow;
import lombok.Getter;
import lombok.Setter;

import java.util.ArrayList;
import java.util.List;

// Generated Aug 27, 2013 3:06:46 PM by Hibernate Tools 3.4.0.CR1

/**
 * Vwsdpoutcomes generated by hbm2java
 */
public class Vwsdpoutcomes implements java.io.Serializable {

	@Getter @Setter private long fid;
	@Getter @Setter private long fstatereportid;
	@Getter @Setter private String femployed;
	@Getter @Setter private String freceivingtraining;
	@Getter @Setter private String freceivingssnpay;
	@Getter @Setter private String freceivingeduaid;
	@Getter @Setter private String freceivingothsupt;
	@Getter @Setter private String freceivingpubfin;
	@Getter @Setter private String freceivingpubfood;
	@Getter @Setter private String freceivingpubhous;
	@Getter @Setter private String fattendingschool;
	@Getter @Setter private String fcompletedhsorged;
	@Getter @Setter private String freceivinglicense;
	@Getter @Setter private String freceivingdegree;
	@Getter @Setter private String fsabusereferral;
	@Getter @Setter private String fincarcerated;
	@Getter @Setter private String fhavingchildren;
	@Getter @Setter private String fhomeless;
	@Getter @Setter private String fconnectiontoadult;
	@Getter @Setter private String fhavingmedicaid;
	@Getter @Setter private String fhealthinsurance;
	@Getter @Setter private String ffostercaretype;
	@Getter @Setter private String demployed;
	@Getter @Setter private String dreceivingtraining;
	@Getter @Setter private String dreceivingssnpay;
	@Getter @Setter private String dreceivingeduaid;
	@Getter @Setter private String dreceivingothsupt;
	@Getter @Setter private String dreceivingpubfin;
	@Getter @Setter private String dreceivingpubfood;
	@Getter @Setter private String dreceivingpubhous;
	@Getter @Setter private String dattendingschool;
	@Getter @Setter private String dcompletedhsorged;
	@Getter @Setter private String dreceivinglicense;
	@Getter @Setter private String dreceivingdegree;
	@Getter @Setter private String dsabusereferral;
	@Getter @Setter private String dincarcerated;
	@Getter @Setter private String dhavingchildren;
	@Getter @Setter private String dhomeless;
	@Getter @Setter private String dconnectiontoadult;
	@Getter @Setter private String dhavingmedicaid;
	@Getter @Setter private String dhealthinsurance;
	@Getter @Setter private String dfostercaretype;
	@Getter @Setter private List<SDPTextChartRow> financialOutcomes;
	@Getter @Setter private List<SDPTextChartRow> educationalOutcomes;
	@Getter @Setter private List<SDPTextChartRow> behaviorOutcomes;
	@Getter @Setter private List<SDPTextChartRow> homelessOutcomes;
	@Getter @Setter private List<SDPTextChartRow> connectionOutcomes;
	@Getter @Setter private List<SDPTextChartRow> insuranceOutcomes;

	public Vwsdpoutcomes() {
	}

	public Vwsdpoutcomes(long fid) {
		this.fid = fid;
	}

	public Vwsdpoutcomes(long fid, long fstatereportid,
			String femployed, String freceivingtraining,
			String freceivingssnpay, String freceivingeduaid,
			String freceivingothsupt, String freceivingpubfin,
			String freceivingpubfood, String freceivingpubhous,
			String fattendingschool, String fcompletedhsorged,
			String freceivinglicense, String freceivingdegree,
			String fsabusereferral, String fincarcerated,
			String fhavingchildren, String fhomeless,
			String fconnectiontoadult, String fhavingmedicaid,
			String fhealthinsurance, String ffostercaretype, String demployed,
			String dreceivingtraining, String dreceivingssnpay,
			String dreceivingeduaid, String dreceivingothsupt,
			String dreceivingpubfin, String dreceivingpubfood,
			String dreceivingpubhous, String dattendingschool,
			String dcompletedhsorged, String dreceivinglicense,
			String dreceivingdegree, String dsabusereferral,
			String dincarcerated, String dhavingchildren, String dhomeless,
			String dconnectiontoadult, String dhavingmedicaid,
			String dhealthinsurance, String dfostercaretype) {
		this.fid = fid;
		this.fstatereportid = fstatereportid;
		this.femployed = femployed;
		this.freceivingtraining = freceivingtraining;
		this.freceivingssnpay = freceivingssnpay;
		this.freceivingeduaid = freceivingeduaid;
		this.freceivingothsupt = freceivingothsupt;
		this.freceivingpubfin = freceivingpubfin;
		this.freceivingpubfood = freceivingpubfood;
		this.freceivingpubhous = freceivingpubhous;
		this.fattendingschool = fattendingschool;
		this.fcompletedhsorged = fcompletedhsorged;
		this.freceivinglicense = freceivinglicense;
		this.freceivingdegree = freceivingdegree;
		this.fsabusereferral = fsabusereferral;
		this.fincarcerated = fincarcerated;
		this.fhavingchildren = fhavingchildren;
		this.fhomeless = fhomeless;
		this.fconnectiontoadult = fconnectiontoadult;
		this.fhavingmedicaid = fhavingmedicaid;
		this.fhealthinsurance = fhealthinsurance;
		this.ffostercaretype = ffostercaretype;
		this.demployed = demployed;
		this.dreceivingtraining = dreceivingtraining;
		this.dreceivingssnpay = dreceivingssnpay;
		this.dreceivingeduaid = dreceivingeduaid;
		this.dreceivingothsupt = dreceivingothsupt;
		this.dreceivingpubfin = dreceivingpubfin;
		this.dreceivingpubfood = dreceivingpubfood;
		this.dreceivingpubhous = dreceivingpubhous;
		this.dattendingschool = dattendingschool;
		this.dcompletedhsorged = dcompletedhsorged;
		this.dreceivinglicense = dreceivinglicense;
		this.dreceivingdegree = dreceivingdegree;
		this.dsabusereferral = dsabusereferral;
		this.dincarcerated = dincarcerated;
		this.dhavingchildren = dhavingchildren;
		this.dhomeless = dhomeless;
		this.dconnectiontoadult = dconnectiontoadult;
		this.dhavingmedicaid = dhavingmedicaid;
		this.dhealthinsurance = dhealthinsurance;
		this.dfostercaretype = dfostercaretype;
	}
	
	public void generateOutcomesChart()
	{
		swapValues();
		NVL();
		financialOutcomes =  new ArrayList<SDPTextChartRow>();
		financialOutcomes.add(new SDPTextChartRow("Reported current part-time or full-time employment", femployed, demployed));
		financialOutcomes.add(new SDPTextChartRow("Reported receiving employment-related training in the past year", freceivingtraining, dreceivingtraining));
		financialOutcomes.add(new SDPTextChartRow("Reported receiving social security payments", freceivingssnpay, dreceivingssnpay));
		financialOutcomes.add(new SDPTextChartRow("Reported receiving financial aid for educational expenses", freceivingeduaid, dreceivingeduaid));
		financialOutcomes.add(new SDPTextChartRow("Reported receiving financial support from another source", freceivingothsupt, dreceivingothsupt));
		financialOutcomes.add(new SDPTextChartRow("Reported receiving public financial assistance<sup>*</sup>", freceivingpubfin, dreceivingpubfin));
		financialOutcomes.add(new SDPTextChartRow("Reported receiving public food assistance<sup>*</sup>", freceivingpubfood, dreceivingpubfood));
		financialOutcomes.add(new SDPTextChartRow("Reported receiving public housing assistance<sup>*</sup>", freceivingpubhous, dreceivingpubhous));
		
		educationalOutcomes = new ArrayList<SDPTextChartRow>();
		educationalOutcomes.add(new SDPTextChartRow("Reported being enrolled in and attending school",fattendingschool,dattendingschool));
		educationalOutcomes.add(new SDPTextChartRow("Reported having completed high school or GED",fcompletedhsorged,dcompletedhsorged));
		educationalOutcomes.add(new SDPTextChartRow("Reported receiving a vocational license or certificate",freceivinglicense,dreceivinglicense));
		educationalOutcomes.add(new SDPTextChartRow("Reported receiving a college degree (e.g., Associate, Bachelor, or higher degree)",freceivingdegree,dreceivingdegree));
		
		
		behaviorOutcomes = new ArrayList<SDPTextChartRow>();
		behaviorOutcomes.add(new SDPTextChartRow("Reported a substance abuse referral",fsabusereferral,dsabusereferral));
		behaviorOutcomes.add(new SDPTextChartRow("Reported having been incarcerated",fincarcerated,dincarcerated));
		behaviorOutcomes.add(new SDPTextChartRow("Reported having children",fhavingchildren,dhavingchildren));
		
		homelessOutcomes =  new ArrayList<SDPTextChartRow>();
		homelessOutcomes.add(new SDPTextChartRow("Reported having been homeless",fhomeless,dhomeless));
		
		connectionOutcomes =  new ArrayList<SDPTextChartRow>();
		connectionOutcomes.add(new SDPTextChartRow("Reported having a current positive connection to an adult",fconnectiontoadult,dconnectiontoadult));
		
		insuranceOutcomes =  new ArrayList<SDPTextChartRow>(); 
		insuranceOutcomes.add(new SDPTextChartRow("Reported having Medicaid",fhavingmedicaid,dhavingmedicaid));
		insuranceOutcomes.add(new SDPTextChartRow("Reported having some other type of health insurance",fhealthinsurance,dhealthinsurance));
		
		
	}
	private void NVL()
	{
		if (femployed == null) { femployed = "N/A"; };
		if (freceivingtraining == null) { freceivingtraining = "N/A"; };
		if (freceivingssnpay == null) { freceivingssnpay = "N/A"; };
		if (freceivingeduaid == null) { freceivingeduaid = "N/A"; };
		if (freceivingothsupt == null) { freceivingothsupt = "N/A"; };
		if (freceivingpubfin == null) { freceivingpubfin = "N/A"; };
		if (freceivingpubfood == null) { freceivingpubfood = "N/A"; };
		if (freceivingpubhous == null) { freceivingpubhous = "N/A"; };
		if (fattendingschool == null) { fattendingschool = "N/A"; };
		if (fcompletedhsorged == null) { fcompletedhsorged = "N/A"; };
		if (freceivinglicense == null) { freceivinglicense = "N/A"; };
		if (freceivingdegree == null) { freceivingdegree = "N/A"; };
		if (fsabusereferral == null) { fsabusereferral = "N/A"; };
		if (fincarcerated == null) { fincarcerated = "N/A"; };
		if (fhavingchildren == null) { fhavingchildren = "N/A"; };
		if (fhomeless == null) { fhomeless = "N/A"; };
		if (fconnectiontoadult == null) { fconnectiontoadult = "N/A"; };
		if (fhavingmedicaid == null) { fhavingmedicaid = "N/A"; };
		if (fhealthinsurance == null) { fhealthinsurance = "N/A"; };
		if (demployed == null) { demployed = "N/A"; };
		if (dreceivingtraining == null) { dreceivingtraining = "N/A"; };
		if (dreceivingssnpay == null) { dreceivingssnpay = "N/A"; };
		if (dreceivingeduaid == null) { dreceivingeduaid = "N/A"; };
		if (dreceivingothsupt == null) { dreceivingothsupt = "N/A"; };
		if (dreceivingpubfin == null) { dreceivingpubfin = "N/A"; };
		if (dreceivingpubfood == null) { dreceivingpubfood = "N/A"; };
		if (dreceivingpubhous == null) { dreceivingpubhous = "N/A"; };
		if (dattendingschool == null) { dattendingschool = "N/A"; };
		if (dcompletedhsorged == null) { dcompletedhsorged = "N/A"; };
		if (dreceivinglicense == null) { dreceivinglicense = "N/A"; };
		if (dreceivingdegree == null) { dreceivingdegree = "N/A"; };
		if (dsabusereferral == null) { dsabusereferral = "N/A"; };
		if (dincarcerated == null) { dincarcerated = "N/A"; };
		if (dhavingchildren == null) { dhavingchildren = "N/A"; };
		if (dhomeless == null) { dhomeless = "N/A"; };
		if (dconnectiontoadult == null) { dconnectiontoadult = "N/A"; };
		if (dhavingmedicaid == null) { dhavingmedicaid = "N/A"; };
		if (dhealthinsurance == null) { dhealthinsurance = "N/A"; };

	}
	private void swapValues()
	{
		String dummy = null;
		if(ffostercaretype != null && ffostercaretype.equalsIgnoreCase("out"))
		{
			dummy = femployed; femployed = demployed; demployed = dummy; 
			dummy = freceivingtraining; freceivingtraining = dreceivingtraining; dreceivingtraining = dummy; 
			dummy = freceivingssnpay; freceivingssnpay = dreceivingssnpay; dreceivingssnpay = dummy; 
			dummy = freceivingeduaid; freceivingeduaid = dreceivingeduaid; dreceivingeduaid = dummy; 
			dummy = freceivingothsupt; freceivingothsupt = dreceivingothsupt; dreceivingothsupt = dummy; 
			dummy = freceivingpubfin; freceivingpubfin = dreceivingpubfin; dreceivingpubfin = dummy; 
			dummy = freceivingpubfood; freceivingpubfood = dreceivingpubfood; dreceivingpubfood = dummy; 
			dummy = freceivingpubhous; freceivingpubhous = dreceivingpubhous; dreceivingpubhous = dummy; 
			dummy = fattendingschool; fattendingschool = dattendingschool; dattendingschool = dummy; 
			dummy = fcompletedhsorged; fcompletedhsorged = dcompletedhsorged; dcompletedhsorged = dummy; 
			dummy = freceivinglicense; freceivinglicense = dreceivinglicense; dreceivinglicense = dummy; 
			dummy = freceivingdegree; freceivingdegree = dreceivingdegree; dreceivingdegree = dummy; 
			dummy = fsabusereferral; fsabusereferral = dsabusereferral; dsabusereferral = dummy; 
			dummy = fincarcerated; fincarcerated = dincarcerated; dincarcerated = dummy; 
			dummy = fhavingchildren; fhavingchildren = dhavingchildren; dhavingchildren = dummy; 
			dummy = fhomeless; fhomeless = dhomeless; dhomeless = dummy; 
			dummy = fconnectiontoadult; fconnectiontoadult = dconnectiontoadult; dconnectiontoadult = dummy; 
			dummy = fhavingmedicaid; fhavingmedicaid = dhavingmedicaid; dhavingmedicaid = dummy; 
			dummy = fhealthinsurance; fhealthinsurance = dhealthinsurance; dhealthinsurance = dummy; 
			
			
		}
	}

}
