package gov.hhs.acf.cb.nytd.models;

import gov.hhs.acf.cb.nytd.models.helper.SDPTextChartRow;
import lombok.Getter;
import lombok.Setter;

import java.util.ArrayList;
import java.util.List;

// Generated Aug 22, 2013 4:39:35 PM by Hibernate Tools 3.4.0.CR1

/**
 * Vwsdpfollowupdemographics generated by hbm2java
 */
public class Vwsdpfollowupdemographics implements java.io.Serializable {

	/*private VwsdpfollowupdemographicsId id;

	public Vwsdpfollowupdemographics() {
	}

	public Vwsdpfollowupdemographics(VwsdpfollowupdemographicsId id) {
		this.id = id;
	}

	public VwsdpfollowupdemographicsId getId() {
		return this.id;
	}

	public void setId(VwsdpfollowupdemographicsId id) {
		this.id = id;
	}*/
	
	private long statereportid;
	private String fmale;
	private String ffemale;
	private String fwhite;
	private String fblack;
	private String famind;
	private String fasian;
	private String fhawaiian;
	private String funknown;
	private String fhispanic;
	private String fdecline;
	private String ffosterCare;
	private String ftribe;
	private String fdeliquent;
	private String fespEdu;
	@Getter @Setter private String freceivedservices;
	@Getter @Setter private String ffosterCareType;
	private String bmale;
	private String bfemale;
	private String bwhite;
	private String bblack;
	private String bamind;
	private String basian;
	private String bhawaiian;
	private String bunknown;
	private String bhispanic;
	private String bdeclined;
	private String bfosterCare;
	private String btribe;
	private String bdeliquent;
	private String bespEdu;
	@Getter @Setter private String breceivedservices;
	@Getter @Setter private String bfosterCareType;
	@Getter @Setter private List<SDPTextChartRow> sex;
	@Getter @Setter private List<SDPTextChartRow> ethnicity;
	@Getter @Setter private List<SDPTextChartRow> services;

	public Vwsdpfollowupdemographics() {
	}

	public Vwsdpfollowupdemographics(long statereportid, String fmale,
			String ffemale, String fwhite, String fblack, String famind,
			String fasian, String fhawaiian, String funknown, String fhispanic,
			String fdecline, String ffosterCare, String ftribe,
			String fdeliquent, String fespEdu, String freceivedservices,
			String bmale, String bfemale, String bwhite, String bblack,
			String bamind, String basian, String bhawaiian, String bunknown,
			String bhispanic, String bdeclined, String bfosterCare,
			String btribe, String bdeliquent, String bespEdu,String breceivedservices,String ffosterCareType,
			String bfosterCareType
			) {
		this.statereportid = statereportid;
		this.fmale = fmale;
		this.ffemale = ffemale;
		this.fwhite = fwhite;
		this.fblack = fblack;
		this.famind = famind;
		this.fasian = fasian;
		this.fhawaiian = fhawaiian;
		this.funknown = funknown;
		this.fhispanic = fhispanic;
		this.fdecline = fdecline;
		this.ffosterCare = ffosterCare;
		this.ftribe = ftribe;
		this.fdeliquent = fdeliquent;
		this.fespEdu = fespEdu;
		this.freceivedservices = freceivedservices;
		this.ffosterCareType = ffosterCareType;
		this.bmale = bmale;
		this.bfemale = bfemale;
		this.bwhite = bwhite;
		this.bblack = bblack;
		this.bamind = bamind;
		this.basian = basian;
		this.bhawaiian = bhawaiian;
		this.bunknown = bunknown;
		this.bhispanic = bhispanic;
		this.bdeclined = bdeclined;
		this.bfosterCare = bfosterCare;
		this.btribe = btribe;
		this.bdeliquent = bdeliquent;
		this.bespEdu = bespEdu;
		this.breceivedservices = breceivedservices;
		this.bfosterCareType = bfosterCareType;
	}

	public long getStatereportid() {
		return this.statereportid;
	}

	public void setStatereportid(long statereportid) {
		this.statereportid = statereportid;
	}

	public String getFmale() {
		return this.fmale;
	}

	public void setFmale(String fmale) {
		this.fmale = fmale;
	}

	public String getFfemale() {
		return this.ffemale;
	}

	public void setFfemale(String ffemale) {
		this.ffemale = ffemale;
	}

	public String getFwhite() {
		return this.fwhite;
	}

	public void setFwhite(String fwhite) {
		this.fwhite = fwhite;
	}

	public String getFblack() {
		return this.fblack;
	}

	public void setFblack(String fblack) {
		this.fblack = fblack;
	}

	public String getFamind() {
		return this.famind;
	}

	public void setFamind(String famind) {
		this.famind = famind;
	}

	public String getFasian() {
		return this.fasian;
	}

	public void setFasian(String fasian) {
		this.fasian = fasian;
	}

	public String getFhawaiian() {
		return this.fhawaiian;
	}

	public void setFhawaiian(String fhawaiian) {
		this.fhawaiian = fhawaiian;
	}

	public String getFunknown() {
		return this.funknown;
	}

	public void setFunknown(String funknown) {
		this.funknown = funknown;
	}

	public String getFhispanic() {
		return this.fhispanic;
	}

	public void setFhispanic(String fhispanic) {
		this.fhispanic = fhispanic;
	}

	public String getFdecline() {
		return this.fdecline;
	}

	public void setFdecline(String fdecline) {
		this.fdecline = fdecline;
	}

	public String getFfosterCare() {
		return this.ffosterCare;
	}

	public void setFfosterCare(String ffosterCare) {
		this.ffosterCare = ffosterCare;
	}

	public String getFtribe() {
		return this.ftribe;
	}

	public void setFtribe(String ftribe) {
		this.ftribe = ftribe;
	}

	public String getFdeliquent() {
		return this.fdeliquent;
	}

	public void setFdeliquent(String fdeliquent) {
		this.fdeliquent = fdeliquent;
	}

	public String getFespEdu() {
		return this.fespEdu;
	}

	public void setFespEdu(String fespEdu) {
		this.fespEdu = fespEdu;
	}

	/*public String getFfosterCareType() {
		return this.ffosterCareType;
	}

	public void setFfosterCareType(String ffosterCareType) {
		this.ffosterCareType = ffosterCareType;
	}
*/
	public String getBmale() {
		return this.bmale;
	}

	public void setBmale(String bmale) {
		this.bmale = bmale;
	}

	public String getBfemale() {
		return this.bfemale;
	}

	public void setBfemale(String bfemale) {
		this.bfemale = bfemale;
	}

	public String getBwhite() {
		return this.bwhite;
	}

	public void setBwhite(String bwhite) {
		this.bwhite = bwhite;
	}

	public String getBblack() {
		return this.bblack;
	}

	public void setBblack(String bblack) {
		this.bblack = bblack;
	}

	public String getBamind() {
		return this.bamind;
	}

	public void setBamind(String bamind) {
		this.bamind = bamind;
	}

	public String getBasian() {
		return this.basian;
	}

	public void setBasian(String basian) {
		this.basian = basian;
	}

	public String getBhawaiian() {
		return this.bhawaiian;
	}

	public void setBhawaiian(String bhawaiian) {
		this.bhawaiian = bhawaiian;
	}

	public String getBunknown() {
		return this.bunknown;
	}

	public void setBunknown(String bunknown) {
		this.bunknown = bunknown;
	}

	public String getBhispanic() {
		return this.bhispanic;
	}

	public void setBhispanic(String bhispanic) {
		this.bhispanic = bhispanic;
	}

	public String getBdeclined() {
		return this.bdeclined;
	}

	public void setBdeclined(String bdeclined) {
		this.bdeclined = bdeclined;
	}

	public String getBfosterCare() {
		return this.bfosterCare;
	}

	public void setBfosterCare(String bfosterCare) {
		this.bfosterCare = bfosterCare;
	}

	public String getBtribe() {
		return this.btribe;
	}

	public void setBtribe(String btribe) {
		this.btribe = btribe;
	}

	public String getBdeliquent() {
		return this.bdeliquent;
	}

	public void setBdeliquent(String bdeliquent) {
		this.bdeliquent = bdeliquent;
	}

	public String getBespEdu() {
		return this.bespEdu;
	}

	public void setBespEdu(String bespEdu) {
		this.bespEdu = bespEdu;
	}

	/*public String getBfosterCareType() {
		return this.bfosterCareType;
	}

	public void setBfosterCareType(String bfosterCareType) {
		this.bfosterCareType = bfosterCareType;
	}*/

	/*public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof VwsdpfollowupdemographicsId))
			return false;
		VwsdpfollowupdemographicsId castOther = (VwsdpfollowupdemographicsId) other;

		return ((this.getStatereportid() == castOther.getStatereportid()) || (this
				.getStatereportid() != null
				&& castOther.getStatereportid() != null && this
				.getStatereportid().equals(castOther.getStatereportid())))
				&& ((this.getFmale() == castOther.getFmale()) || (this
						.getFmale() != null && castOther.getFmale() != null && this
						.getFmale().equals(castOther.getFmale())))
				&& ((this.getFfemale() == castOther.getFfemale()) || (this
						.getFfemale() != null && castOther.getFfemale() != null && this
						.getFfemale().equals(castOther.getFfemale())))
				&& ((this.getFwhite() == castOther.getFwhite()) || (this
						.getFwhite() != null && castOther.getFwhite() != null && this
						.getFwhite().equals(castOther.getFwhite())))
				&& ((this.getFblack() == castOther.getFblack()) || (this
						.getFblack() != null && castOther.getFblack() != null && this
						.getFblack().equals(castOther.getFblack())))
				&& ((this.getFamind() == castOther.getFamind()) || (this
						.getFamind() != null && castOther.getFamind() != null && this
						.getFamind().equals(castOther.getFamind())))
				&& ((this.getFasian() == castOther.getFasian()) || (this
						.getFasian() != null && castOther.getFasian() != null && this
						.getFasian().equals(castOther.getFasian())))
				&& ((this.getFhawaiian() == castOther.getFhawaiian()) || (this
						.getFhawaiian() != null
						&& castOther.getFhawaiian() != null && this
						.getFhawaiian().equals(castOther.getFhawaiian())))
				&& ((this.getFunknown() == castOther.getFunknown()) || (this
						.getFunknown() != null
						&& castOther.getFunknown() != null && this
						.getFunknown().equals(castOther.getFunknown())))
				&& ((this.getFhispanic() == castOther.getFhispanic()) || (this
						.getFhispanic() != null
						&& castOther.getFhispanic() != null && this
						.getFhispanic().equals(castOther.getFhispanic())))
				&& ((this.getFdecline() == castOther.getFdecline()) || (this
						.getFdecline() != null
						&& castOther.getFdecline() != null && this
						.getFdecline().equals(castOther.getFdecline())))
				&& ((this.getFfosterCare() == castOther.getFfosterCare()) || (this
						.getFfosterCare() != null
						&& castOther.getFfosterCare() != null && this
						.getFfosterCare().equals(castOther.getFfosterCare())))
				&& ((this.getFtribe() == castOther.getFtribe()) || (this
						.getFtribe() != null && castOther.getFtribe() != null && this
						.getFtribe().equals(castOther.getFtribe())))
				&& ((this.getFdeliquent() == castOther.getFdeliquent()) || (this
						.getFdeliquent() != null
						&& castOther.getFdeliquent() != null && this
						.getFdeliquent().equals(castOther.getFdeliquent())))
				&& ((this.getFespEdu() == castOther.getFespEdu()) || (this
						.getFespEdu() != null && castOther.getFespEdu() != null && this
						.getFespEdu().equals(castOther.getFespEdu())))
				&& ((this.getFfosterCareType() == castOther
						.getFfosterCareType()) || (this.getFfosterCareType() != null
						&& castOther.getFfosterCareType() != null && this
						.getFfosterCareType().equals(
								castOther.getFfosterCareType())))
				&& ((this.getBmale() == castOther.getBmale()) || (this
						.getBmale() != null && castOther.getBmale() != null && this
						.getBmale().equals(castOther.getBmale())))
				&& ((this.getBfemale() == castOther.getBfemale()) || (this
						.getBfemale() != null && castOther.getBfemale() != null && this
						.getBfemale().equals(castOther.getBfemale())))
				&& ((this.getBwhite() == castOther.getBwhite()) || (this
						.getBwhite() != null && castOther.getBwhite() != null && this
						.getBwhite().equals(castOther.getBwhite())))
				&& ((this.getBblack() == castOther.getBblack()) || (this
						.getBblack() != null && castOther.getBblack() != null && this
						.getBblack().equals(castOther.getBblack())))
				&& ((this.getBamind() == castOther.getBamind()) || (this
						.getBamind() != null && castOther.getBamind() != null && this
						.getBamind().equals(castOther.getBamind())))
				&& ((this.getBasian() == castOther.getBasian()) || (this
						.getBasian() != null && castOther.getBasian() != null && this
						.getBasian().equals(castOther.getBasian())))
				&& ((this.getBhawaiian() == castOther.getBhawaiian()) || (this
						.getBhawaiian() != null
						&& castOther.getBhawaiian() != null && this
						.getBhawaiian().equals(castOther.getBhawaiian())))
				&& ((this.getBunknown() == castOther.getBunknown()) || (this
						.getBunknown() != null
						&& castOther.getBunknown() != null && this
						.getBunknown().equals(castOther.getBunknown())))
				&& ((this.getBhispanic() == castOther.getBhispanic()) || (this
						.getBhispanic() != null
						&& castOther.getBhispanic() != null && this
						.getBhispanic().equals(castOther.getBhispanic())))
				&& ((this.getBdeclined() == castOther.getBdeclined()) || (this
						.getBdeclined() != null
						&& castOther.getBdeclined() != null && this
						.getBdeclined().equals(castOther.getBdeclined())))
				&& ((this.getBfosterCare() == castOther.getBfosterCare()) || (this
						.getBfosterCare() != null
						&& castOther.getBfosterCare() != null && this
						.getBfosterCare().equals(castOther.getBfosterCare())))
				&& ((this.getBtribe() == castOther.getBtribe()) || (this
						.getBtribe() != null && castOther.getBtribe() != null && this
						.getBtribe().equals(castOther.getBtribe())))
				&& ((this.getBdeliquent() == castOther.getBdeliquent()) || (this
						.getBdeliquent() != null
						&& castOther.getBdeliquent() != null && this
						.getBdeliquent().equals(castOther.getBdeliquent())))
				&& ((this.getBespEdu() == castOther.getBespEdu()) || (this
						.getBespEdu() != null && castOther.getBespEdu() != null && this
						.getBespEdu().equals(castOther.getBespEdu())))
				&& ((this.getBfosterCareType() == castOther
						.getBfosterCareType()) || (this.getBfosterCareType() != null
						&& castOther.getBfosterCareType() != null && this
						.getBfosterCareType().equals(
								castOther.getBfosterCareType()))
								)
								;
	}

	public int hashCode() {
		int result = 17;

		result = 37
				* result
				+ (getStatereportid() == null ? 0 : this.getStatereportid()
						.hashCode());
		result = 37 * result
				+ (getFmale() == null ? 0 : this.getFmale().hashCode());
		result = 37 * result
				+ (getFfemale() == null ? 0 : this.getFfemale().hashCode());
		result = 37 * result
				+ (getFwhite() == null ? 0 : this.getFwhite().hashCode());
		result = 37 * result
				+ (getFblack() == null ? 0 : this.getFblack().hashCode());
		result = 37 * result
				+ (getFamind() == null ? 0 : this.getFamind().hashCode());
		result = 37 * result
				+ (getFasian() == null ? 0 : this.getFasian().hashCode());
		result = 37 * result
				+ (getFhawaiian() == null ? 0 : this.getFhawaiian().hashCode());
		result = 37 * result
				+ (getFunknown() == null ? 0 : this.getFunknown().hashCode());
		result = 37 * result
				+ (getFhispanic() == null ? 0 : this.getFhispanic().hashCode());
		result = 37 * result
				+ (getFdecline() == null ? 0 : this.getFdecline().hashCode());
		result = 37
				* result
				+ (getFfosterCare() == null ? 0 : this.getFfosterCare()
						.hashCode());
		result = 37 * result
				+ (getFtribe() == null ? 0 : this.getFtribe().hashCode());
		result = 37
				* result
				+ (getFdeliquent() == null ? 0 : this.getFdeliquent()
						.hashCode());
		result = 37 * result
				+ (getFespEdu() == null ? 0 : this.getFespEdu().hashCode());
		result = 37
				* result
				+ (getFfosterCareType() == null ? 0 : this.getFfosterCareType()
						.hashCode());
		result = 37 * result
				+ (getBmale() == null ? 0 : this.getBmale().hashCode());
		result = 37 * result
				+ (getBfemale() == null ? 0 : this.getBfemale().hashCode());
		result = 37 * result
				+ (getBwhite() == null ? 0 : this.getBwhite().hashCode());
		result = 37 * result
				+ (getBblack() == null ? 0 : this.getBblack().hashCode());
		result = 37 * result
				+ (getBamind() == null ? 0 : this.getBamind().hashCode());
		result = 37 * result
				+ (getBasian() == null ? 0 : this.getBasian().hashCode());
		result = 37 * result
				+ (getBhawaiian() == null ? 0 : this.getBhawaiian().hashCode());
		result = 37 * result
				+ (getBunknown() == null ? 0 : this.getBunknown().hashCode());
		result = 37 * result
				+ (getBhispanic() == null ? 0 : this.getBhispanic().hashCode());
		result = 37 * result
				+ (getBdeclined() == null ? 0 : this.getBdeclined().hashCode());
		result = 37
				* result
				+ (getBfosterCare() == null ? 0 : this.getBfosterCare()
						.hashCode());
		result = 37 * result
				+ (getBtribe() == null ? 0 : this.getBtribe().hashCode());
		result = 37
				* result
				+ (getBdeliquent() == null ? 0 : this.getBdeliquent()
						.hashCode());
		result = 37 * result
				+ (getBespEdu() == null ? 0 : this.getBespEdu().hashCode());
		result = 37
				* result
				+ (getBfosterCareType() == null ? 0 : this.getBfosterCareType()
						.hashCode());
		return result;
	}*/

	public void generateSDPDemographicChart()
	{
		swapValues();
		NVL();
		sex = new ArrayList<SDPTextChartRow>();
		sex.add(new SDPTextChartRow("Male", fmale, bmale));
		sex.add(new SDPTextChartRow("Female", ffemale, bfemale));
		
		ethnicity = new ArrayList<SDPTextChartRow>();
		ethnicity.add(new SDPTextChartRow("American Indian or Alaska Native",famind ,bamind));
		ethnicity.add(new SDPTextChartRow("Asian",fasian ,basian));
		ethnicity.add(new SDPTextChartRow("Black or African American",fblack ,bblack));
		ethnicity.add(new SDPTextChartRow("Native Hawaiian or Other Pacific Islander",fhawaiian ,bhawaiian ));
		ethnicity.add(new SDPTextChartRow("White",fwhite ,bwhite));
		ethnicity.add(new SDPTextChartRow("Unknown or Declined",funknown ,bunknown ));
		ethnicity.add(new SDPTextChartRow("Hispanic or Latino ethnicity<sup>*</sup>",fhispanic ,bhispanic ));
		
		services = new ArrayList<SDPTextChartRow>();
		services.add(new SDPTextChartRow("<b>Receiving Services</b>",freceivedservices ,breceivedservices));
	}
	private void NVL()
	{
		if (fmale == null) { fmale = "N/A"; };
		if (ffemale == null) { ffemale = "N/A"; };
		if (fwhite == null) { fwhite = "N/A"; };
		if (fblack == null) { fblack = "N/A"; };
		if (famind == null) { famind = "N/A"; };
		if (fasian == null) { fasian = "N/A"; };
		if (fhawaiian == null) { fhawaiian = "N/A"; };
		if (funknown == null) { funknown = "N/A"; };
		if (fhispanic == null) { fhispanic = "N/A"; };
		if (fdecline == null) { fdecline = "N/A"; };
		if (ffosterCare == null) { ffosterCare = "N/A"; };
		if (ftribe == null) { ftribe = "N/A"; };
		if (fdeliquent == null) { fdeliquent = "N/A"; };
		if (fespEdu == null) { fespEdu = "N/A"; };
		if (freceivedservices == null) { freceivedservices = "N/A"; };
		if (bmale == null) { bmale = "N/A"; };
		if (bfemale == null) { bfemale = "N/A"; };
		if (bwhite == null) { bwhite = "N/A"; };
		if (bblack == null) { bblack = "N/A"; };
		if (bamind == null) { bamind = "N/A"; };
		if (basian == null) { basian = "N/A"; };
		if (bhawaiian == null) { bhawaiian = "N/A"; };
		if (bunknown == null) { bunknown = "N/A"; };
		if (bhispanic == null) { bhispanic = "N/A"; };
		if (bdeclined == null) { bdeclined = "N/A"; };
		if (bfosterCare == null) { bfosterCare = "N/A"; };
		if (btribe == null) { btribe = "N/A"; };
		if (bdeliquent == null) { bdeliquent = "N/A"; };
		if (bespEdu == null) { bespEdu = "N/A"; };
		if (breceivedservices == null) { breceivedservices = "N/A"; };
	}
	private void swapValues()
	{
		String dummy = null;
		if(ffosterCareType != null && ffosterCareType.equalsIgnoreCase("out"))
		{
			dummy = fmale; fmale = bmale; bmale = dummy;
			dummy = ffemale; ffemale = bfemale; bfemale = dummy;
			dummy = fwhite; fwhite = bwhite; bwhite = dummy;
			dummy = fblack; fblack = bblack; bblack = dummy;
			dummy = famind; famind = bamind; bamind = dummy;
			dummy = fasian; fasian = basian; basian = dummy;
			dummy = fhawaiian; fhawaiian = bhawaiian; bhawaiian = dummy;
			dummy = funknown; funknown = bunknown; bunknown = dummy;
			dummy = fhispanic; fhispanic = bhispanic; bhispanic = dummy;
			dummy = fdecline; fdecline = bdeclined; bdeclined = dummy;
			dummy = ffosterCare; ffosterCare = bfosterCare; bfosterCare = dummy;
			dummy = ftribe; ftribe = btribe; btribe = dummy;
			dummy = fdeliquent; fdeliquent = bdeliquent; bdeliquent = dummy;
			dummy = fespEdu; fespEdu = bespEdu; bespEdu = dummy;
			dummy = freceivedservices; freceivedservices = breceivedservices;breceivedservices  = dummy;


			
		}
	}

}
